{{ content() }}

<ul class="pager">
    <li class="previous pull-left">
        {{ link_to("usuario/index", "&larr; Voltar") }}
    </li>
    <li class="pull-right">
        {{ link_to("usuario/create", "Criar perfis", "class": "btn btn-primary") }}
    </li>
</ul>

{% for perfil in page.items %}
{% if loop.first %}
<table class="table table-bordered table-striped" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Ativo?</th>
        </tr>
    </thead>
{% endif %}
    <tbody>
        <tr>
            <td>{{ perfil.id }}</td>
            <td>{{ perfil.nome }}</td>
            <td>{{ perfil.ativo == 'Y' ? 'Yes' : 'No' }}</td>
            <td width="12%">{{ link_to("perfil/edit/" ~ perfil.id, '<i class="icon-pencil"></i> Editar', "class": "btn") }}</td>
            <td width="12%">{{ link_to("perfil/delete/" ~ perfil.id, '<i class="icon-remove"></i> Deletar', "class": "btn") }}</td>
        </tr>
    </tbody>
{% if loop.last %}
    <tbody>
        <tr>
            <td colspan="10" align="right">
                <div class="btn-group">
                    {{ link_to("perfil/search", '<i class="icon-fast-backward"></i> Primeiro', "class": "btn") }}
                    {{ link_to("perfil/search?page=" ~ page.before, '<i class="icon-step-backward"></i> Anterior', "class": "btn ") }}
                    {{ link_to("perfil/search?page=" ~ page.next, '<i class="icon-step-forward"></i> Próximo', "class": "btn") }}
                    {{ link_to("perfil/search?page=" ~ page.last, '<i class="icon-fast-forward"></i> Último', "class": "btn") }}
                    <span class="help-inline">{{ page.current }}/{{ page.total_pages }}</span>
                </div>
            </td>
        </tr>
    <tbody>
</table>
{% endif %}
{% else %}
    Nenhum perfil encontrado
{% endfor %}
