<section class="main bg">
    {% for mensagem in mensagens %}
    {% if loop.first %}
        <div class="bg-primary clearfix padder m-b">
            <h3 class="m-b">{{mensagem['titulo']}}</h3>
        </div>
    {%else%}
        <div class="bg-default white-header clearfix padder m-b divider">
            <h3 class="m-b">{{mensagem['titulo']}}</h3>
        </div>
    {% endif %}
    <div class="text-small padder">
            <div class="block clearfix">
                {% if( mensagem['avatar'] is empty ) %}
                    {% set avatar_user = 'bfdc40e956b123b24b4962cc9409485a.jpg' %} 
                {% else  %}
                    {% set avatar_user = empresaId~'/'~mensagem['id']~'/'~'60_'~mensagem['avatar'] %} 
                {% endif %}
                <a href="#" class="thumb-mini inline">{{image( 'img/users/'~avatar_user, 'class':'img-circle', 'alt':mensagem['nomeRemetente']) }}</a> {{mensagem['nomeRemetente']}}
                &lt;{{mensagem['emailRemetente']}}&gt; <strong>para</strong> {{mensagem['usuariosDestinatarios']}}
                <div class="pull-right inline">{{ mensagem['envioDt'] }} (<em><span class="moment">{{ mensagem['envioDtBanco'] }}</span></em>) 
                    {% if loop.last %}
                    <div class="btn-group">
                        <button type="button" class="btn btn-white btn-xs dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="#" class="link-responder-mensagem"><i class="fa fa-fw fa-reply"></i>Responder</a></li>
                            <li class="divider"></li>
                            <li><a href="#" id="btnExcluirMensagem"><i class="fa fa-fw fa-trash-o"></i>Excluir</a></li>
                        </ul>
                    </div>
                    {% endif %}
                </div>
            </div>
            <p>
                {{mensagem['mensagem']}}
            </p>
    </div>
        {% if loop.last %}
            <div class="padder">
                <form class="panel text-small">
                    <div class="panel-body">Clique aqui para <a href="#" class="link-responder-mensagem">Responder</a></div>
                </form>
            </div>
            <div class="padder block clearfix" id="div-resposta-mensagem" style="display: none;">
                {{ form('empresa/mensagem/responder-mensagem', 'class':'form-horizontal media', 'id':'form-responder-mensagem', 'method': 'post') }}
                    {{hidden_field("id",'value':mensagem['id_mensagem_pai'])}} 
                    <div class="col-lg-12">
                        <p>
                            {{ text_field("resposta-titulo", 'id':'resposta-titulo', 'placeholder': 'Informe um título', 'value':'','class': 'bg-focus form-control', 'style':'width:60%') }}
                        </p>
                    </div>
                    <div class="col-lg-12">
                        <p>
                        {{ text_area("resposta-mensagem", 'id':'resposta-mensagem', 'placeholder': 'Descreva a resposta da mensagem','value':'','rows':'6', 'class':'bg-focus form-control') }}
                        </p>
                    </div>
                    <div class="text-center padder">
                        <button type="button" class="btn btn-sm btn-default m-t" id="btnCancelarResposta"> Cancelar</button>
                        <button type="submit" class="btn btn-sm btn-facebook m-t" id="btnResponderMensagem"> Enviar</button>
                    </div>
                {{endForm()}}
            </div><br/>
        {% endif %}
    {% endfor %}
</section>
<!-- Início Modal Criar Desafio -->
<div class="modal fade" id="modalExcluirMsg" tabindex="-5" role="dialog" data-backdrop="false"  aria-labelledby="modalExcluirMsgLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title" id="myModalLabel"></h4>
            </div>
            <div class="modal-body" id="modal-body-exclusao">Deseja realmente excluir a mensagem?</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-default squared" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-sm btn-syndicate squared" id="btnExcluirMensagemLida">Excluir</button>
            </div>
        </div>
    </div>
</div>
{{ javascript_include('js/empresa/mensagem/ler-mensagem.js') }}
<script type="text/javascript">  
    $(document).ready(function(){
        LerMensagem.init();
    });   
</script>