{{hidden_field("tipo-mensagem",'value':1)}}
<div class="row">  
<!-- / nav -->
  <section id="content" class="content-sidebar bg-white">
    <!-- .sidebar -->
    <aside class="sidebar bg-lighter sidebar-small">
      <div class="text-center clearfix bg-white">
          <button class="btn btn-sm btn-facebook m-t m-b" id="btnNovaMensagem"><i class="fa fa-edit"></i> Novo</button>
      </div>
      <div class="list-group list-normal m-b-none">
          <a href="#" class="list-group-item btnMensagem active" id="btnMensagensEntrada"><i class="fa fa-fw fa-inbox"></i><span class="badge m-r">{{count_mensagens_recebidas}}</span> Entrada</a>
        <a href="#" class="list-group-item btnMensagem" id="btnMensagensEnviadas"><i class="fa fa-fw fa-envelope-o"></i><span class="badge m-r">{{count_mensagens_enviadas}}</span> Enviadas</a>
        <a href="#" class="list-group-item btnMensagem" id="btnMensagensExcluidas"><i class="fa fa-fw fa-trash-o"></i><span class="badge m-r">{{count_mensagens_excluidas}}</span> Excluídas</a>
      </div>
    </aside>
    <!-- /.sidebar -->
    <!-- .sidebar -->
    <aside class="sidebar sidebar-large">
      <div class="padder header-bar bg clearfix" id="grupo-filtros">
          <div class="btn-group m-t m-b">
          <button class="btn btn-white btn-sm dropdown-toggle" data-toggle="dropdown">Filtro <span class="caret"></span></button>
          <ul class="dropdown-menu text-left text-small">
              <li><a href="#" id="btnFiltroLidas">Lidas</a></li>
              <li><a href="#" id="btnFiltroNaoLidas">Não lidas</a></li>
          </ul>
        </div>
        <button class="btn btn-sm btn-white" data-toggle="tooltip" data-title="Atualizar"><i class="fa fa-refresh"></i></button>
      </div>
      <div class="list-normal m-t-n-xmini scroll-y scrollbar" style="max-height:400px">
          <?php echo $this->flashSession->output(); ?>
          <div id="lista-mensagens" ></div>
      </div>
    </aside>
    <div id="ler-mensagem" style="display: none"></div>
    <!-- /.sidebar -->
    
  </section>
</div>
{{ javascript_include('js/empresa/mensagem/mensagem.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        Mensagem.init();
    });
</script>