<section class="main media">
    <div class="row media">
        <div class="col-sm-11">
            {{ form('empresa/mensagem/salvar-mensagem', 'class':'form-horizontal media', 'id':'form-nova-mensagem', 'method': 'post') }}
            <div class="form-group">
                <label class="col-lg-3 control-label">{{lang['enviar_para']}}:</label>
                <div class="col-lg-9">
                     <?php 
                        echo Phalcon\Tag::select(array('id'=>'destinatarios-mensagem',
                                                    'class'=>'form-control select2-multiple required',
                                                    'multiple'=>'multiple',
                                                    'using' => ['id', 'nome'],
                                                    'value' =>[],
                                                    'name'=>'dados[destinatarios-mensagem][]','style'=>'width:90%'),
                               array());
                         ?>
                    <label id="destinatarios-mensagem-error" class="error" for="destinatarios-mensagem" style="display: none;"></label>
                </div>
            </div>
            <div class="form-group" id="div_colab_resp">
                <label class="col-lg-3 control-label">{{lang['titulo']}}:</label>
                <div class="col-lg-9 select2-allowclear">
                    {{ text_field("dados[titulo]", 'id':'titulo','value':'','class': 'bg-focus form-control', 'style':'width:60%') }}
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">{{lang['mensagem']}}:</label>
                <div class="col-lg-9">
                    {{ text_area("dados[mensagem]", 'id':'mensagem', 'placeholder': lang['descreva_mensagem'],'value':'','rows':'6', 'class':'bg-focus form-control') }}
                </div>
            </div>
            <div class="text-center clearfix bg-white">
                <input type="button" class="btn btn-theme04 btn-default btn-sm squared" id="btnCancelarNovaMensagem" value="{{lang['cancelar']}}">
                <input type="submit" class="btn btn-theme04 btn-facebook btn-sm squared" value="{{lang['enviar_mensagem']}}">
            </div>
            {{endForm()}}
        </div>
    </div>
     {{hidden_field("lang",'value':lang['lang'])}}
</section>

<!-- Fim Modal Criar Regra -->
{{ javascript_include('js/empresa/mensagem/nova-mensagem.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        NovaMensagem.init($("#lang").val());
    });
</script>