<div class="clearfix">
    <h4><i class="fa fa-edit"></i>Desafios</h4>
</div>
<div class="row">
    <div class="col-lg-12">
        <!-- .breadcrumb -->
        <ul class="breadcrumb">
            <li><a href="#">Desafios</a></li>
        </ul>
        <!-- / .breadcrumb -->
    </div>
    <div class="col-lg-10 col-lg-offset-1">
        <?php echo $this->flashSession->output(); ?>
        <!-- scrollable inbox widget -->
        <section class="panel">
            <header class="panel-heading">
                <div class="pull-left col-lg-4">
                    {% if perfilId == perfilGerente %}
                        <button type="button" class="btn btn-sm btn-facebook squared" id="btnCriarDesafio">Criar Desafio</button>
                    {% endif %}
                    {% if perfilId == perfilAdmin %}
                        <button type="button" class="btn btn-sm btn-facebook squared" id="btnMapearPontuacaoDesafio">Mapear Pontuação</button>
                    {% endif %}
                </div>
                <div class="col-lg-4 input-group">
                    <input type="text" id="filterDesafio" class="input-sm form-control" placeholder="Pesquisar por desafios">
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-sm btn-white" id="btnPesquisarDesafio">Pesquisar</button>
                    </span>
                </div>
            </header>
            <div id="pesquisarDesafio"></div>
        </section>
    </div>
</div>
<!-- Início Modal Criar Desafio -->
<div class="modal fade" id="modalCriarDesafio" tabindex="-5" role="dialog" aria-labelledby="modalCriarDesafioLabel" aria-hidden="true">
    {{ form('empresa/desafio/salvar-desafio', 'class':'form-horizontal', 'id':'form-desafio', 'method': 'post') }}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title" id="myModalLabel"></h4>
            </div>
            <div class="modal-body" id="modal-body-desafio"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-default squared" data-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-sm btn-syndicate squared" id="btnSalvarDesafio">Salvar desafio</button>
            </div>
        </div>
    </div>
    {{endForm()}}
</div>
<!-- Fim Modal Criar Desafio -->
<!-- Início Modal Criar Desafio -->
<div class="modal fade" id="modalMapearPontuacaoDesafio" tabindex="-5" role="dialog" aria-labelledby="modalMapearPontuacaoDesafio" aria-hidden="true">
    {{ form('empresa/desafio/modal-mapear-pontuacao-desafio', 'class':'form-horizontal', 'id':'form-mapear-pontuacao-desafio', 'method': 'post') }}
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                    <h4 class="modal-title" id="myModalLabelMapearDesafio"></h4>
                </div>
                <div class="modal-body" id="modal-body-mapear-desafio"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-default squared" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-sm btn-syndicate squared" id="btnSalvarDesafio">Salvar</button>
                </div>
            </div>
        </div>
    {{endForm()}}
</div>
<!-- Fim Modal Criar Desafio -->
{{ javascript_include('js/empresa/desafio/desafio.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        Desafio.init();
    });
</script>