<section class="main padder">
    <div class="row">
        <div class="col-sm-12">
            {% for tipoDesafio in tipo_desafios %}
                <div class="form-group">
                    <label class="col-lg-5 control-label" data-placement="left" data-toggle="tooltip" data-original-title="Pontuação em que desafio é considerado {{tipoDesafio.desafioTipo|convert_encoding('latin1', 'utf8')}}.">{{tipoDesafio.desafioTipo|convert_encoding('latin1', 'utf8')}}:</label>
                    <div class="col-lg-7">
                        <div class="spinner input-group col-lg-3 form-control-static" id="MySpinner">
                            {{ text_field("dados[tipos]["~tipoDesafio.id~"]", 'id':tipoDesafio.id,'value':tipoDesafio.pontuacao, 'class':"required messa tipoDesafio input-sm spinner-input form-control", 'title':'Campo Obrigatório') }}
                            <div class="btn-group btn-group-vertical input-group-btn">
                                <button class="btn btn-white spinner-up" type="button">
                                    <i class="fa fa-chevron-up"></i>
                                </button>
                                <button class="btn btn-white spinner-down" type="button">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </div>
                        </div>
                         <label id="ideia-error" class="error" style="display: none;" for="{{tipoDesafio.id}}">Campo obrigatório</label>
                    </div>   
                </div>
            {% endfor %}
        </div>
    </div>
</section>
{{ javascript_include('js/empresa/desafio/mapear-pontuacao.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        ModalMapearPontuacaoDesafio.init();
    });
</script>