{{hidden_field("dados[id]",'value':id,'id':'hidden_id')}}
<section class="main padder">
    <div class="row">
        <div class="col-sm-11">
            <div class="form-group">
                <label class="col-lg-3 control-label">Nível do Desafio</label>
                <div class="col-lg-9 select2-allowclear">
                  <?php 
                        echo Phalcon\Tag::select(array(
                        "desafioTipoId",
                        'class'=>'form-control',
                        'name'=>'dados[desafio_tipo_id]','value'=>$desafioTipoId,
                        $nivel_desafios,
                        "using" => array("id", "desafioTipo"),
                        'useEmpty' => true,
                        'emptyText' => 'Selecione o nível do desafio...',
                        'emptyValue' => ''
                    )); ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Tipo de Desafio</label>
                <div class="col-lg-9 select2-allowclear">
                  <?php 
    
                     echo Phalcon\Tag::select(array('id'=>'tipoDesafio',
                                                    'class'=>'form-control',
                                                    'name'=>'dados[tipo_desafio]','value'=>$tipo) ,
                                              array(''=>'Selecione o tipo de desafio...',
                                                    1 => "Individual", 
                                                    2 => "Por equipe")) ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Colaboradores participantes</label>
                <div class="col-lg-9 select2-allowclear">
                    {{ text_field("dados[colaboradores-participantes]", 'id':'colaboradores-participantes','value':colaboradores,'class': 'multi', 'style':'width:353px;') }}
                </div>
            </div>
            <div class="form-group" id="div_colab_resp">
                <label class="col-lg-3 control-label">Colaborador responsável</label>
                <div class="col-lg-9 select2-allowclear">
                    {{ text_field("dados[colaborador-responsavel]", 'id':'colaborador-responsavel','value':colaborador_responsavel,'class': 'multi', 'style':'width:353px;') }}
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Desafio</label>
                <div class="col-lg-9">
                    {{ text_area("dados[desafio]", 'id':'desafio', 'placeholder': 'Ex: Concluir vinte vendas até o final do mês.','value':desafio,'rows':'3', 'class':'bg-focus form-control') }}
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Data início</label>
                <div class="col-lg-4">
                    {{ text_field("dados[data_inicio]", 'id':'data_inicio','value':inicioDt,'data-date-format': 'dd/mm/yyyy','autocomplete':'off', 'class':'form-control datepickerDesafio') }}
                </div>   
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Data fim</label>
                <div class="col-lg-4">
                    {{ text_field('dados[data_fim]', 'id':'data_fim','value':fimDt,'data-date-format': 'dd/mm/yyyy','autocomplete':'off', 'class':'form-control datepickerDesafio') }}
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Premiação</label>
                <div class="col-lg-9">
                    {{ text_area("dados[premiacao]", 'id':'premiacao','value':premiacao, 'placeholder': 'Ex: Almoço pago pela empresa em uma sexta-feira.','rows':'2', 'class':'form-control') }}
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Fim Modal Criar Regra -->
{{ javascript_include('js/empresa/desafio/modal-desafio.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        ModalDesafio.init();
    });
</script>