
<table class="table table-responsive table-striped table-condensed">
    <tbody>
        {% for desafio in page.items %}
            <tr class="row">
                <td class="td-responsive">
                    <div class="pull-right text-muted">
                        <strong class="h3 text-info text-center" data-placement="left" data-toggle="tooltip" data-original-title="Pontos válidos">{{desafio.pontuacao}}</strong> pts<br>
                        <small>
                            {% if(desafio.status == 'N') %}
                            {% set status = 'danger' %} 
                            {% set status_label = 'Inativo' %}
                            {% else  %}
                            {% set status = 'success' %} 
                            {% set status_label = 'Ativo' %}
                            {% endif %}
                            <span class="label label-{{status}}" data-placement="left" data-toggle="tooltip" data-original-title="Status">
                                {{status_label}}
                            </span>
                        </small>
                    </div>
                    <div class="text-muted">
                            {% if(desafio.tipo is 1) %}
                                {% set status = 'info' %} 
                                {% set status_label = 'Individual' %}
                            {% elseif(desafio.tipo is 2)  %}
                                {% set status = 'success' %} 
                                {% set status_label = 'Por Equipe' %}
                            {% endif %}
                            <span class="label label-{{status}}" data-placement="left" data-toggle="tooltip" title="Tipo de Desafio"> {{status_label}}</span>
                    </div>
                    <span data-placement="left" data-toggle="tooltip" data-original-title="Período Válido" >{{desafio.inicioDt}} a {{desafio.fimDt}} </span> 
                    <div class="btn-group" data-placement="right" data-toggle="tooltip" data-original-title="Ações">
                        <button class="dropdown-toggle" role="button" data-toggle="dropdown" ><i class="fa fa-gear"></i></button>
                        <ul class="dropdown-menu pull-left">
                            <li class="text-left"><a href="#" class="btnAlterarDesafio" id="{{desafio.id}}"><i class="icon-pencil"></i> Alterar</a></li>
                             <li class="divider"></li>
                            {% if(desafio.status == 'N') %}
                                <li class="text-left">{{linkTo('empresa/desafio/ativar-inativar-desafio/Y/'~desafio.id, '<i class="icon-plus-sign"></i> Ativar')}}
                            {% else %}
                                <li class="text-left">{{linkTo('empresa/desafio/ativar-inativar-desafio/N/'~desafio.id, '<i class="fa fa-minus-square-o"></i> Inativar')}}</li>
                            {% endif %}
<!--                           
                            <li class="text-left"><a href="#" id="{{desafio.id}}"><i class="icon-remove"></i> Deletar</a> </li>-->
                        </ul>
                    </div>
                    <h6>{{desafio.desafio}}</h6>
                </td>
            </tr>
        {% elsefor %}
            <tr class="row">
                <td class="table-responsive">
                    <h6 class="text-center text-info">Nenhum desafio cadastrado.</h6>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<section class="panel-footer">
    <footer>
        <div class="row">
            <div class="col-sm-4 col-sm-offset-3 text-center">
                <small class="text-muted inline m-t-small m-b-small">Mostrando {{ page.current }} de {{ page.total_pages }}</small>
            </div>
            <div class="col-sm-5 text-right text-center-sm">                
                <ul class="pagination pagination-small m-t-none m-b-none">
                    <li><a href="#" class="fa btnPaginacaoDesafio" id="1"><i class="icons icon-fast-backward"></i> Primeiro</a></li>
                    <li><a href="#" class="fa btnPaginacaoDesafio" id="{{page.before}}"><i class="icons icon-step-backward"></i> Anterior</a></li>
                    <li><a href="#" class="fa btnPaginacaoDesafio" id="{{page.next}}"><i class="icons icon-step-forward"></i> Próximo</a></li>
                    <li><a href="#" class="fa btnPaginacaoDesafio" id="{{page.last}}">Último <i class="icons icon-fast-forward"></i> </a></li>
                </ul>
                {{hidden_field("quantDesafio","value":page.total_items )}}
            </div>
        </div>
    </footer>
</section>
{{ javascript_include('js/empresa/desafio/pesquisar-desafio.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        pesquisarDesafio.init();
    });
</script>