<section class="panel">
{% for mensagem in mensagens %}
    <div class="panel-body">

        {% if loop.first %}
            <div class="mail-header row">
                <div class="col-lg-12 bg-lighter">
                    <h4 class="pull-left text-primary"> {{mensagem['titulo']}}</h4>
                </div>
            </div>
        {%else%}
            <div class="mail-header row">
                <div class="col-lg-12 bg-lighter">
                    <h4 class="pull-left text-primary"> {{mensagem['titulo']}}</h4>
                </div>
            </div>
        {% endif %}

        <div class="email-cabecalho">
            <div class="row">
                <div class="col-lg-8">
                    {% if( mensagem['avatar'] is empty ) %}
                        {% set avatar_user = 'bfdc40e956b123b24b4962cc9409485a.jpg' %} 
                    {% else  %}
                        {% set avatar_user = empresaId~'/'~mensagem['id']~'/'~'60_'~mensagem['avatar'] %} 
                    {% endif %}
                    <a href="#" class="thumb thumb-mini inline">{{image( 'img/users/'~avatar_user, 'class':'img-circle','width':'30px', 'alt':mensagem['nomeRemetente']) }}</a> {{mensagem['nomeRemetente']}}
                    &lt;{{mensagem['emailRemetente']}}&gt; <strong>para</strong> {{mensagem['usuariosDestinatarios']}}
                </div>
                <div class="col-lg-4">                 
                    <div class="pull-right inline">{{ mensagem['envioDt'] }} (<em><span class="moment">{{ mensagem['envioDtBanco'] }}</span></em>) 
                    </div>
                </div>
            </div>
        </div>
        <div class="view-mail">
            <p>{{mensagem['mensagem']}}</p>
        </div>
        <div class="compose-btn pull-left">
            {% if loop.last %}
                {% if resposta %}
                    <a class="btn btn-sm btn-facebook link-responder-mensagem" data-title="Responder mensagem" data-toggle="tooltip" data-placement="left" href="#"><i class="fa fa-reply"></i> Responder</a>
                {% endif %}
            {% endif %}
            <button id="btnExcluirMensagem" data-title="Excluir mensagem" data-toggle="tooltip" data-placement="right" class="btn btn-sm"><i class="fa fa-trash-o"></i></button>
        </div>
    </div>
</section>
{% if loop.last %}
    {% if resposta %}
        <div class="padder block clearfix" id="div-resposta-mensagem" style="display: none;">
            {{ form('colaborador/mensagem/responder-mensagem', 'class':'form-horizontal media', 'id':'form-responder-mensagem', 'method': 'post') }}
                {{hidden_field("id",'value':mensagem['id_mensagem_pai'])}} 
                <div class="col-lg-12">
                    <p>
                        {{ text_field("resposta-titulo", 'id':'resposta-titulo', 'placeholder': 'Informe um título', 'value':'','class': 'bg-focus form-control', 'style':'width:60%') }}
                    </p>
                </div>
                <div class="col-lg-12">
                    <p>
                        {{ text_area("resposta-mensagem", 'id':'resposta-mensagem', 'placeholder': 'Descreva a resposta da mensagem','value':'','rows':'6', 'class':'bg-focus form-control') }}
                    </p>
                </div>
                <div class="text-center padder">
                    <button type="button" class="btn btn-sm btn-default m-t squared" id="btnCancelarResposta"> Cancelar</button>
                    <button type="submit" class="btn btn-sm btn-facebook m-t squared" id="btnResponderMensagem"> Enviar</button>
                </div>
            {{endForm()}}
        </div><br/>
    {% else%}
        {{hidden_field("id",'value':mensagem['id_mensagem_pai'])}}
    {% endif %}
{% endif %}
</section>
{% endfor %}
<div class="modal fade" id="modalExcluirMsg" tabindex="-5" role="dialog" data-backdrop="false"  aria-labelledby="modalExcluirMsgLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title" id="myModalLabel"></h4>
            </div>
            <div class="modal-body ml" id="modal-body-exclusao"><br/><p>Deseja realmente excluir a mensagem?</p></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-default squared" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-sm btn-syndicate squared" id="btnExcluirMensagemLida">Excluir</button>
            </div>
        </div>
    </div>
</div>
{{ javascript_include('js/colaborador/mensagem/ler-mensagem.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        LerMensagem.init();
    });
</script>