<section class="tasks-widget">
    <div class="panel-body">
        <div class="task-content">
            <ul class="task-list ui-sortable" id="sortable">
                {% for mensagem in page.items %}
                    {% if mensagem.lida is 'Y' %}
                        {% set list = 'success' %}
                    {% else %}
                        {% set list = 'info' %}
                    {% endif %}
                    <li class="list-unstyled list-{{list}}">
                        <div class="task-title">
                            <a href="#" class="mensagem-entrada" id="{{mensagem.id}}"><small class="pull-right text-muted moment">{{ mensagem.envioDt }}</small><strong>{{mensagem.nome}}</strong><br><small>{{mensagem.titulo}}</small></a>
                        </div>
                    </li>
                {% elsefor %}
                    <li class="text-center center">
                    <div class="task-title">
                        <span class="task-title-sp">{{lang['nenhuma_mensagem']}}</span>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
         <footer>
        <div class="row">
            <div class="col-sm-3 col-sm-offset-4 text-center">
                <small class="text-muted inline m-t-small m-b-small">{{lang['p_mostrando']}} {{ page.current }} de {{ page.total_pages }}</small>
            </div>
            <div class="col-sm-5 text-right text-center-sm">                
                <ul class="pagination pagination-small m-t-none m-b-none">
                    <div class="btn-group m-t pull-right">
                    <button type="button" class="btn btn-sm btn-default btnPaginacaoMensagem" id="{{page.before}}"><i class="fa fa-chevron-left"></i></button>
                    <button type="button" class="btn btn-sm btn-default btnPaginacaoMensagem" id="{{page.next}}"><i class="fa fa-chevron-right"></i></button>
                    </div>
                </ul>
            </div>
        </div>
        </footer>
    </div>
    {{hidden_field("lang",'value':lang['lang'])}}
</section>
{{ javascript_include('js/colaborador/mensagem/pesquisar-mensagem.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        pesquisarMensagem.init($("#lang").val());
    });
</script>