{{ content() }}
{{ form('usuario/changePassword', 'class': 'form-horizontal form-login','role': 'form', 'autocomplete': 'off') }}
<form method="post" autocomplete="off" action="{{ url("usuario/changePassword") }}">

    <div class="center scaffold">

        <h2>Alterar senha</h2>

        <div class="clearfix">
            <label for="senha">Senha</label>
            {{ form.render("senha") }}
        </div>

        <div class="clearfix">
            <label for="confirmPassword">Confirmar senha</label>
            {{ form.render("confirmPassword") }}
        </div>

        <div class="clearfix">
            {{ submit_button("Alterar senha", "class": "btn btn-primary") }}
        </div>

    </div>

</form>