
<form method="post" autocomplete="off">

<ul class="pager">
    <li class="previous pull-left">
        {{ link_to("usuario", "&larr; Voltar") }}
    </li>
    <li class="pull-right">
        {{ submit_button("Salvar", "class": "btn btn-big btn-success") }}
    </li>
</ul>

{{ content() }}

<div class="center scaffold">
    <h2>Editar usuário</h2>

    <ul class="nav nav-tabs">
        <li class="active"><a href="#A" data-toggle="tab">Básico</a></li>
        <li><a href="#B" data-toggle="tab">Logins de sucesso</a></li>
        <li><a href="#C" data-toggle="tab">Alterações de senha</a></li>
        <li><a href="#D" data-toggle="tab">Redefinições de senha</a></li>
    </ul>

<div class="tabbable">
    <div class="tab-content">
        <div class="tab-pane active" id="A">

            {{ form.render("id") }}

            <div class="span4">

                <div class="clearfix">
                    <label for="nome">Nome</label>
                    {{ form.render("nome") }}
                </div>

                <div class="clearfix">
                    <label for="perfilId">Perfil</label>
                    {{ form.render("perfilId") }}
                </div>

                <div class="clearfix">
                    <label for="suspenso">Suspenso?</label>
                    {{ form.render("suspenso") }}
                </div>

            </div>

            <div class="span4">

                <div class="clearfix">
                    <label for="email">E-Mail</label>
                    {{ form.render("email") }}
                </div>

                <div class="clearfix">
                    <label for="banido">Banido?</label>
                    {{ form.render("banido") }}
                </div>

                <div class="clearfix">
                    <label for="ativo">Confirmado?</label>
                    {{ form.render("ativo") }}
                </div>

            </div>
        </div>

        <div class="tab-pane" id="B">
            <p>
                <table class="table table-bordered table-striped" align="center">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>IP Address</th>
                            <th>User Agent</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for login in user.successLogins %}
                        <tr>
                            <td>{{ login.id }}</td>
                            <td>{{ login.ipAddress }}</td>
                            <td>{{ login.userAgent }}</td>
                        </tr>
                    {% else %}
                        <tr><td colspan="3" align="center">O usuário não tem logins com sucesso</td></tr>
                    {% endfor %}
                    </tbody>
                </table>
            </p>
        </div>

        <div class="tab-pane" id="C">
            <p>
                <table class="table table-bordered table-striped" align="center">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>IP Address</th>
                            <th>User Agent</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for change in user.passwordChanges %}
                        <tr>
                            <td>{{ change.id }}</td>
                            <td>{{ change.ipAddress }}</td>
                            <td>{{ change.userAgent }}</td>
                            <td>{{ date("Y-m-d H:i:s", change.criacaoDt) }}</td>
                        </tr>
                    {% else %}
                        <tr><td colspan="3" align="center">O usuário não mudou sua senha</td></tr>
                    {% endfor %}
                    </tbody>
                </table>
            </p>
        </div>

        <div class="tab-pane" id="D">
            <p>
                <table class="table table-bordered table-striped" align="center">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Data</th>
                            <th>Redefiniu?</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for reset in user.resetPasswords %}
                        <tr>
                            <th>{{ reset.id }}</th>
                            <th>{{ date("Y-m-d H:i:s", reset.criacaoDt) }}
                            <th>{{ reset.reset == 'Y' ? 'Yes' : 'No' }}
                        </tr>
                    {% else %}
                        <tr><td colspan="3" align="center">Usuário não redefiniu sua senha</td></tr>
                    {% endfor %}
                    </tbody>
                </table>
            </p>
        </div>

    </div>
</div>

    </form>
</div>