<div id="preloader">
			<div id="status">&nbsp;</div>
		</div>
		<section id="components" class="components">
			<div class="container">
				<div class="jumbotron">
					<h1 class="text-left">Bootstrap 3! Components</h1>
					<p>A lightweight, flexible component to showcase key content on your site. It works well on marketing and content-heavy sites. 
					This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.<br><br>
					Seen enough?</p>
					<p><a href="http://themeforest.net/item/syndicate-all-purpose-bootstrap-retina-template/5412688?ref=awerest" class="btn btn-success">Purchase</a> or <a href="index.html" class="btn btn-danger">Go back on site</a></p>
				</div>
				<div class="row">
					<div class="col-lg-6">
						<p>Basic progress bars:</p>
						<div class="progress">
							<div class="progress-bar" style="width: 60%;"></div>
						</div>
						<p>Additional colors:</p>
						<div class="progress">
							<div class="progress-bar progress-bar-info" style="width: 20%"></div>
						</div>
						<div class="progress">
							<div class="progress-bar progress-bar-success" style="width: 40%"></div>
						</div>
						<div class="progress">
							<div class="progress-bar progress-bar-warning" style="width: 60%"></div>
						</div>
						<div class="progress">
							<div class="progress-bar progress-bar-danger" style="width: 80%"></div>
						</div>
						<p>Animated:</p>
						<div class="progress progress-striped active">
							<div class="progress-bar" style="width: 45%"></div>
						</div>
					</div>
					<div class="col-lg-6">
						<p>Striped bars:</p>
						<div class="progress progress-striped">
							<div class="progress-bar progress-bar" style="width: 60%;"></div>
						</div>
						<p>Additional colors:</p>
						<div class="progress progress-striped">
							<div class="progress-bar progress-bar-info" style="width: 20%"></div>
						</div>
						<div class="progress progress-striped">
							<div class="progress-bar progress-bar-success" style="width: 40%"></div>
						</div>
						<div class="progress progress-striped">
							<div class="progress-bar progress-bar-warning" style="width: 60%"></div>
						</div>
						<div class="progress progress-striped">
							<div class="progress-bar progress-bar-danger" style="width: 80%"></div>
						</div>
						<p>Stacked:</p>
						<div class="progress">
							<div class="progress-bar progress-bar-success" style="width: 35%"></div>
							<div class="progress-bar progress-bar-warning" style="width: 20%"></div>
							<div class="progress-bar progress-bar-danger" style="width: 10%"></div>
						</div>
					</div>
				</div>
				<div class="small-divider"></div>
				<div class="row">
					<div class="col-lg-6">
						<h1>Wells</h1>
						<div class="well well-large">
							Look, I'm in a large well!
						</div>
						<div class="well">
							Look, I'm in a well!
						</div>
						<div class="well well-small">
							Look, I'm in a small well!
						</div>
					</div>
					<div class="col-lg-6">
						<h1>Alerts</h1>
						<div class="alert">
							<button type="button" class="close" data-dismiss="alert">&times;</button>
							<strong>Warning!</strong> Best check yo self, you're not looking too good.
						</div>
						<div class="alert alert-danger">
							<button type="button" class="close" data-dismiss="alert">&times;</button>
							<strong>Oh snap!</strong> Change a few things up and try submitting again.
						</div>
						<div class="alert alert-success">
							<button type="button" class="close" data-dismiss="alert">&times;</button>
							<strong>Well done!</strong> You successfully read this important alert message.
						</div>
						<div class="alert alert-info">
							<button type="button" class="close" data-dismiss="alert">&times;</button>
							<strong>Heads up!</strong> This alert needs your attention, but it's not super important.
						</div>
					</div>
				</div>
				<div class="small-divider"></div>
				<div class="row">
					<div class="col-lg-12">
						<h1>Typography</h1>
					</div>
					<div class="col-lg-6 margin">
						<p class="text-muted">Fusce dapibus, tellus ac cursus commodo, tortor mauris nibh.</p>
						<p class="text-primary">Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
						<p class="text-warning">Etiam porta sem malesuada magna mollis euismod.</p>
						<p class="text-danger">Donec ullamcorper nulla non metus auctor fringilla.</p>
						<p class="text-success">Duis mollis, est non commodo luctus, nisi erat porttitor ligula.</p>
						<p class="text-info">Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
					</div>
					<div class="col-lg-6 margin">
						<p><small>This line of text is meant to be treated as fine print.</small></p>
						<p>The following snippet of text is <strong>rendered as bold text</strong>.</p>
						<p>The following snippet of text is <em>rendered as italicized text</em>.</p>
						<p>An abbreviation of the word attribute is <abbr title="attribute">attr</abbr>.</p>
						<p>Code example, <code>&lt;section&gt;</code> should be wrapped as inline.</p>
						<span class="label">Default</span>
						<span class="label label-success">Success</span>
						<span class="label label-warning">Warning</span>
						<span class="label label-danger">Danger</span>
						<span class="label label-info">Info</span>
					</div>
					<div class="col-lg-12 margin">
						<p class="text-right">Right aligned text.</p>
						<p class="text-center">Center aligned text.</p>
						<p class="text-left">Left aligned text.</p>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-2 margin">
						<h1 class="text-left">Title 1</h1>
					</div>
					<div class="col-lg-2 margin">
						<h2>Title 2</h2>
					</div>
					<div class="col-lg-2 margin">
						<h3>Title 3</h3>
					</div>
					<div class="col-lg-2 margin">
						<h4>Title 4</h4>
					</div>
					<div class="col-lg-2 margin">
						<h5>Title 5</h5>
					</div>
					<div class="col-lg-2 margin">
						<h6>Title 6</h6>
					</div>
				</div>
				<div class="small-divider"></div>
				<div class="row">
					<div class="col-lg-12">
						<h1>Panels</h1>
						<p class="text-center">All colors and with footter or header</p>
					</div>
					<div class="col-lg-6 margin">
						<div class="panel">
							<div class="panel-heading">Panel heading</div>
							Panel content
						</div>
						<div class="panel">
							Panel content
							<div class="panel-footer">Panel footer</div>
						</div>
						<div class="panel panel-primary">
							<div class="panel-heading">Panel heading</div>
							Panel content
						</div>
					</div>
					<div class="col-lg-6 margin">
						<div class="panel panel-success">
							<div class="panel-heading">Panel heading</div>
							Panel content
						</div>
						<div class="panel panel-warning">
							<div class="panel-heading">Panel heading</div>
							Panel content
						</div>
						<div class="panel panel-danger">
							<div class="panel-heading">Panel heading</div>
							Panel content
						</div>
						<div class="panel panel-info">
							<div class="panel-heading">Panel heading</div>
							Panel content
						</div>
					</div>
				</div>
				<div class="small-divider"></div>
				<div class="row">
					<div class="col-lg-12">
						<h1>Quotes</h1>
						<p class="text-center">Left, right and with or without source</p>
					</div>
					<div class="col-lg-6 margin">
						<blockquote>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
						</blockquote>
						<blockquote class="pull-left">
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
							<small>Someone famous in <cite title="Source Title">Source Title</cite></small>
						</blockquote>
					</div>
					<div class="col-lg-6 margin">
						<blockquote class="pull-right">
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
						</blockquote>
						<blockquote class="pull-right">
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
							<small>Someone famous in <cite title="Source Title">Source Title</cite></small>
						</blockquote>
					</div>
				</div>
				<div class="small-divider"></div>
				<div class="row">
					<div class="col-lg-6 margin text-center">
						<h1>Tooltips and popovers</h1>
						<a href="#" class="btn btn-danger" data-thumb="popover" data-toggle="popover" data-placement="top" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." title="" data-original-title="Popover on top">Popover top </a>
						<a href="#" class="btn btn-danger" data-thumb="popover" data-toggle="popover" data-placement="bottom" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." title="" data-original-title="Popover on bottom"> Popover bottom </a>
						<a href="#" class="btn btn-danger" data-thumb="popover" data-toggle="popover" data-placement="right" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." title="" data-original-title="Popover on right"> Popover right </a>
						<a href="#" class="btn btn-danger" data-thumb="popover" data-toggle="popover" data-placement="left" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." title="" data-original-title="Popover on left"> Popover left</a>
						<br><br><br>
						<a href="#" data-thumb="tooltip" data-toggle="tooltip" data-placement="top" title="" data-original-title="Tooltip on top">Tooltip on top | </a>
						<a href="#" data-thumb="tooltip" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Tooltip on bottom">Tooltip on bottom | </a>
						<a href="#" data-thumb="tooltip" data-toggle="tooltip" data-placement="left" title="" data-original-title="Tooltip on left">Tooltip on left | </a>
						<a href="#" data-thumb="tooltip" data-toggle="tooltip" data-placement="right" title="" data-original-title="Tooltip on right">Tooltip on right</a>
					</div>
					<div class="col-lg-6 margin">
						<h1>Accordion</h1>
						<div class="accordion" id="accordion2">
							<div class="accordion-group">
								<div class="accordion-heading">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
										Collapsible Group Item #1
									</a>
								</div>
								<div id="collapseOne" class="accordion-body collapse">
									<div class="accordion-inner">
										Aoccdrnig to a rscheearch at Cmabrigde Uinervtisy, it deosn't mttaer in waht oredr the ltteers in a wrod are, the olny iprmoetnt tihng is taht the frist and lsat ltteer be at the rghit pclae.
									</div>
								</div>
							</div>
							<div class="accordion-group">
								<div class="accordion-heading">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
										Collapsible Group Item #2
									</a>
								</div>
								<div id="collapseTwo" class="accordion-body collapse">
									<div class="accordion-inner">
										Aoccdrnig to a rscheearch at Cmabrigde Uinervtisy, it deosn't mttaer in waht oredr the ltteers in a wrod are, the olny iprmoetnt tihng is taht the frist and lsat ltteer be at the rghit pclae.
									</div>
								</div>
							</div>
							<div class="accordion-group">
								<div class="accordion-heading">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
										Collapsible Group Item #3
									</a>
								</div>
								<div id="collapseThree" class="accordion-body collapse">
									<div class="accordion-inner">
										Aoccdrnig to a rscheearch at Cmabrigde Uinervtisy, it deosn't mttaer in waht oredr the ltteers in a wrod are, the olny iprmoetnt tihng is taht the frist and lsat ltteer be at the rghit pclae.
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="small-divider"></div>
				<div class="row">
					<div class="col-lg-12">
						<h1>Tabs and pills</h1>
					</div>
					<p class="text-center">On top, bottom, left aligned and justified</p>
					<div class="col-lg-6 margin">
						<ul class="nav nav-tabs">
							<li class="active"><a href="#tab1" data-toggle="tab">Section 1</a></li>
							<li><a href="#tab2" data-toggle="tab">Section 2</a></li>
							<li><a href="#tab3" data-toggle="tab">Section 3</a></li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane fade in active" id="tab1">
								<p>I'm in Section 1. Aoccdrnig to a rscheearch at Cmabrigde Uinervtisy, it deosn't mttaer in waht oredr the ltteers in a wrod are</p>
							</div>
							<div class="tab-pane fade" id="tab2">
								<p>Howdy, Section 2. The olny iprmoetnt tihng is taht the frist and lsat ltteer be at the rghit pclae. The rset can be a toatl mses and you can sitll raed it wouthit porbelm.</p>
							</div>
							<div class="tab-pane fade" id="tab3">
								<p>What's up, this is Section 3. Tihs is bcuseae the huamn mnid deos not raed ervey lteter by istlef, but the wrod as a wlohe. Awesomeness, true story!</p>
							</div>
						</div>
					</div>
					<div class="col-lg-6 margin">
						<div class="tab-content">
							<div class="tab-pane fade in active" id="tab4">
								<p>I'm in Section 1. Aoccdrnig to a rscheearch at Cmabrigde Uinervtisy, it deosn't mttaer in waht oredr the ltteers in a wrod are</p>
							</div>
							<div class="tab-pane fade" id="tab5">
								<p>Howdy, Section 2. The olny iprmoetnt tihng is taht the frist and lsat ltteer be at the rghit pclae. The rset can be a toatl mses and you can sitll raed it wouthit porbelm.</p>
							</div>
							<div class="tab-pane fade" id="tab6">
								<p>What's up, this is Section 3. Tihs is bcuseae the huamn mnid deos not raed ervey lteter by istlef, but the wrod as a wlohe. Awesomeness, true story!</p>
							</div>
						</div>
						<ul class="nav nav-justified nav-tabs">
							<li class="active"><a href="#tab4" data-toggle="tab">Section 1</a></li>
							<li><a href="#tab5" data-toggle="tab">Section 2</a></li>
							<li><a href="#tab6" data-toggle="tab">Section 3</a></li>
						</ul>
					</div>
				</div>
				<div class="small-divider"></div>
				<div class="row">
					<div class="col-lg-6 margin">
						<ul id="left-tabs" class="nav nav-pills">
							<li class="active"><a href="#tab7" data-toggle="tab">Section 1</a></li>
							<li><a href="#tab8" data-toggle="tab">Section 2</a></li>
							<li><a href="#tab9" data-toggle="tab">Section 3</a></li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane fade in active" id="tab7">
								<p>I'm in Section 1. Aoccdrnig to a rscheearch at Cmabrigde Uinervtisy, it deosn't mttaer in waht oredr the ltteers in a wrod are</p>
							</div>
							<div class="tab-pane fade" id="tab8">
								<p>Howdy, Section 2. The olny iprmoetnt tihng is taht the frist and lsat ltteer be at the rghit pclae. The rset can be a toatl mses and you can sitll raed it wouthit porbelm.</p>
							</div>
							<div class="tab-pane fade" id="tab9">
								<p>What's up, this is Section 3. Tihs is bcuseae the huamn mnid deos not raed ervey lteter by istlef, but the wrod as a wlohe. Awesomeness, true story!</p>
							</div>
						</div>
					</div>
					<div class="col-lg-6 margin">
						<div class="tab-content">
							<div class="tab-pane fade in active" id="tab10">
								<p>I'm in Section 1. Aoccdrnig to a rscheearch at Cmabrigde Uinervtisy, it deosn't mttaer in waht oredr the ltteers in a wrod are</p>
							</div>
							<div class="tab-pane fade" id="tab11">
								<p>Howdy, Section 2. The olny iprmoetnt tihng is taht the frist and lsat ltteer be at the rghit pclae. The rset can be a toatl mses and you can sitll raed it wouthit porbelm.</p>
							</div>
							<div class="tab-pane fade" id="tab12">
								<p>What's up, this is Section 3. Tihs is bcuseae the huamn mnid deos not raed ervey lteter by istlef, but the wrod as a wlohe. Awesomeness, true story!</p>
							</div>
						</div>
						<ul id="right-tabs" class="nav nav-justified nav-pills">
							<li class="active"><a href="#tab10" data-toggle="tab">Section 1</a></li>
							<li><a href="#tab11" data-toggle="tab">Section 2</a></li>
							<li><a href="#tab12" data-toggle="tab">Section 3</a></li>
						</ul>
					</div>
				</div>
				<div class="small-divider"></div>
				<div class="row">
					<div class="col-lg-12">
						<h1>Buttons</h1>
					</div>
					<div class="col-lg-6 text-center margin">
						<p>Square buttons</p>
						<button type="button" class="btn btn-default squared">Default</button>
						<button type="button" class="btn btn-primary squared">Primary</button>
						<button type="button" class="btn btn-success squared">Success</button>
						<button type="button" class="btn btn-info squared">Info</button>
						<button type="button" class="btn btn-warning squared">Warning</button>
						<button type="button" class="btn btn-danger squared">Danger</button>
					</div>
					<div class="col-lg-6 text-center margin">
						<p>Rounded buttons</p>
						<button type="button" class="btn btn-default">Default</button>
						<button type="button" class="btn btn-primary">Primary</button>
						<button type="button" class="btn btn-success">Success</button>
						<button type="button" class="btn btn-info">Info</button>
						<button type="button" class="btn btn-warning">Warning</button>
						<button type="button" class="btn btn-danger">Danger</button>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12 text-center margin">
						<p>We just had to add some of our own fancy colored buttons ;)</p>
						<button type="button" class="btn btn-syndicate squared">Syndicate</button>
						<button type="button" class="btn btn-fancy squared">Fancy</button>
						<button type="button" class="btn btn-cool squared">Cool</button>
						<button type="button" class="btn btn-eco squared">Think Eco</button>
						<button type="button" class="btn btn-sun squared">Suny</button>
						<button type="button" class="btn btn-pallmall squared">Pall Mall</button>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-6 text-center margin">
						<p>Disabled buttons</p>
						<button type="button" class="btn btn-default" disabled="disabled">Default</button>
						<button type="button" class="btn btn-primary" disabled="disabled">Primary</button>
						<button type="button" class="btn btn-success" disabled="disabled">Success</button>
						<button type="button" class="btn btn-info" disabled="disabled">Info</button>
						<button type="button" class="btn btn-warning" disabled="disabled">Warning</button>
						<button type="button" class="btn btn-danger" disabled="disabled">Danger</button>
					</div>
					<div class="col-lg-6 text-center margin">
						<p>Button sizes</p>
						<button type="button" class="btn btn-primary btn-large">Large button</button>
						<button type="button" class="btn btn-primary">Default button</button>
						<button type="button" class="btn btn-primary btn-small">Small button</button>
						<button type="button" class="btn btn-primary btn-mini">Mini button</button>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-6 text-center margin">
						<p>Button groups and buttons with icon</p>
						<div class="btn-group">
							<button type="button" class="btn btn-warning">Left</button>
							<button type="button" class="btn btn-warning">Middle</button>
							<button type="button" class="btn btn-warning">Right</button>
						</div>
						<a href="#" class="btn btn-success"><i class="icon-share"></i></a>
						<a href="#" class="btn btn-success"><i class="icon-remove icon-white"></i></a>
						<a href="#" class="btn btn-success"><i class="icon-chevron-right"></i></a><br>
						<a href="#" class="btn btn-info"><i class="icon-trash"></i> Delete</a>
						<a href="#" class="btn btn-info"><i class="icon-plus"></i> Add Item</a>
						<a href="#" class="btn btn-info">Listen <i class="icon-headphones"></i></a>
					</div>
					<div class="col-lg-6 text-center margin">
						<p>Split and single button dropdowns</p>
						<div class="btn-group">
							<button type="button" class="btn btn-default">Action</button>
							<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li class="divider"></li>
								<li><a href="#">Separated link</a></li>
							</ul>
						</div>
						<div class="btn-group">
							<button type="button" class="btn btn-primary">Action</button>
							<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li class="divider"></li>
								<li><a href="#">Separated link</a></li>
							</ul>
						</div>
						<div class="btn-group">
							<button type="button" class="btn btn-danger">Danger</button>
							<button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li class="divider"></li>
								<li><a href="#">Separated link</a></li>
							</ul>
						</div>
						<div class="btn-group">
							<button type="button" class="btn btn-warning">Warning</button>
							<button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
							<ul class="dropdown-menu">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li class="divider"></li>
							<li><a href="#">Separated link</a></li>
							</ul>
						</div>
						<div class="btn-group">
							<button type="button" class="btn btn-success">Success</button>
							<button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li class="divider"></li>
								<li><a href="#">Separated link</a></li>
							</ul>
						</div>
						<div class="btn-group">
							<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li class="divider"></li>
								<li><a href="#">Separated link</a></li>
							</ul>
						</div>
						<div class="btn-group">
							<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li class="divider"></li>
								<li><a href="#">Separated link</a></li>
							</ul>
						</div>
						<div class="btn-group">
							<button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">Danger <span class="caret"></span></button>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li class="divider"></li>
								<li><a href="#">Separated link</a></li>
							</ul>
						</div>
						<div class="btn-group">
							<button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown">Warning <span class="caret"></span></button>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li class="divider"></li>
								<li><a href="#">Separated link</a></li>
							</ul>
						</div>
						<div class="btn-group">
							<button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">Success <span class="caret"></span></button>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li class="divider"></li>
								<li><a href="#">Separated link</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="small-divider"></div>
				<div class="row">
					<div class="col-lg-12">
						<h1>Tables</h1>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-6">
						<h1>Default</h1>
						<table class="table">
							<thead>
								<tr>
									<th>#</th>
									<th>First Name</th>
									<th>Last Name</th>
									<th>Username</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>1</td>
									<td>Mark</td>
									<td>Otto</td>
									<td>@mdo</td>
								</tr>
								<tr>
									<td>2</td>
									<td>Jacob</td>
									<td>Thornton</td>
									<td>@fat</td>
								</tr>
								<tr>
									<td>3</td>
									<td>Larry</td>
									<td>the Bird</td>
									<td>@twitter</td>
								</tr>
							</tbody>
						</table>
					</div>
					<div class="col-lg-6">
						<h1>Striped</h1>
						<table class="table table-striped">
							<thead>
								<tr>
									<th>#</th>
									<th>First Name</th>
									<th>Last Name</th>
									<th>Username</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>1</td>
									<td>Mark</td>
									<td>Otto</td>
									<td>@mdo</td>
								</tr>
								<tr>
									<td>2</td>
									<td>Jacob</td>
									<td>Thornton</td>
									<td>@fat</td>
								</tr>
								<tr>
									<td>3</td>
									<td>Larry</td>
									<td>the Bird</td>
									<td>@twitter</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-6">
						<h1>Bordered</h1>
						<table class="table table-bordered">
							<thead>
								<tr>
									<th>#</th>
									<th>First Name</th>
									<th>Last Name</th>
									<th>Username</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>1</td>
									<td>Mark</td>
									<td>Otto</td>
									<td>@mdo</td>
								</tr>
								<tr>
									<td>2</td>
									<td>Jacob</td>
									<td>Thornton</td>
									<td>@fat</td>
								</tr>
								<tr>
									<td>3</td>
									<td>Larry</td>
									<td>the Bird</td>
									<td>@twitter</td>
								</tr>
							</tbody>
						</table>
					</div>
					<div class="col-lg-6">
						<h1>Hover</h1>
						<table class="table table-hover">
							<thead>
								<tr>
									<th>#</th>
									<th>First Name</th>
									<th>Last Name</th>
									<th>Username</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>1</td>
									<td>Mark</td>
									<td>Otto</td>
									<td>@mdo</td>
								</tr>
								<tr>
									<td>2</td>
									<td>Jacob</td>
									<td>Thornton</td>
									<td>@fat</td>
								</tr>
								<tr>
									<td>3</td>
									<td>Larry</td>
									<td>the Bird</td>
									<td>@twitter</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-6">
						<h1>Condensed</h1>
						<table class="table table-condensed">
							<thead>
								<tr>
									<th>#</th>
									<th>First Name</th>
									<th>Last Name</th>
									<th>Username</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>1</td>
									<td>Mark</td>
									<td>Otto</td>
									<td>@mdo</td>
								</tr>
								<tr>
									<td>2</td>
									<td>Jacob</td>
									<td>Thornton</td>
									<td>@fat</td>
								</tr>
								<tr>
									<td>3</td>
									<td>Larry</td>
									<td>the Bird</td>
									<td>@twitter</td>
								</tr>
							</tbody>
						</table>
					</div>
					<div class="col-lg-6">
						<h1>Contextual</h1>
						<table class="table">
							<thead>
								<tr>
									<th>#</th>
									<th>First Name</th>
									<th>Last Name</th>
									<th>Username</th>
								</tr>
							</thead>
							<tbody>
								<tr class="success">
									<td>1</td>
									<td>Mark</td>
									<td>Otto</td>
									<td>@mdo</td>
								</tr>
								<tr class="danger">
									<td>2</td>
									<td>Jacob</td>
									<td>Thornton</td>
									<td>@fat</td>
								</tr>
								<tr class="warning">
									<td>3</td>
									<td>Larry</td>
									<td>the Bird</td>
									<td>@twitter</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<div class="jumbotron">
					<h1 class="text-left">See more</h1>
					<p>For more <strong>CSS snippets</strong> visit <a href="http://getbootstrap.com/css/" class="btn btn-primary btn-default" target="_blank">link</a><br>
					For more <strong>components</strong> visit <a href="http://getbootstrap.com/components/" class="btn btn-primary btn-default" target="_blank">link</a><br>
					For more <strong>JavaScript</strong> visit <a href="http://getbootstrap.com/javascript/" class="btn btn-primary btn-default" target="_blank">link</a><br><br>
					Seen enough?</p>
					<p><a href="http://themeforest.net/item/syndicate-all-purpose-bootstrap-retina-template/5412688?ref=awerest" class="btn btn-success">Purchase</a> or <a href="index.html" class="btn btn-danger">Go back on site</a></p>
				</div>
			</div>
		</section>
	<!--start back to top button-->
		<a href="#components" class="hidden-sm go-top" data-0="opacity: 0;" data-1000="opacity: 1;">Go Top</a>
	<!--end back to top button-->
	<!--Start scripts - IMPORTANT: all scripts MUST be loaded after latest jQuery-->
	<!--latest jQuery-->
		<script src="js/jquery-1.10.2.min.js"></script>
	<!--main bootstrap js-->
		<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/js/bootstrap.min.js"></script>
	<!--modernizr-->
		<script src="js/modernizr.js" type="text/javascript"></script>
	<!--retina-->
		<script src="js/retina.js" type="text/javascript"></script>
	<!--smooth scroll on page-->
		<script src="js/jquery.easing.js" type="text/javascript"></script>
		<script>
		$(function() {
			$('.navbar a, .navbar li a, .brand, #footer li a, .more a, a.go-top').bind('click',function(event){
			var $anchor = $(this);

			$('[data-spy="scroll"]').each(function () {
			var $spy = $(this).scrollspy('refresh')
			});

			$('html, body').stop().animate({
			scrollTop: $($anchor.attr('href')).offset().top -60
			}, 1500,'easeInOutExpo');

			event.preventDefault();
			});
		});
		</script>
	<!--responsive embed videos-->
		<script src="js/jquery.fitvids.min.js" type="text/javascript"></script>
		<script>
			$(document).ready(function(){
				$(".video").fitVids();
			});
		</script>
	<!--scrollbar-->
		<script src="js/jquery.nicescroll.min.js" type="text/javascript"></script>
		<script>
		$(document).ready(
			function() {	
				$("html, .modal").niceScroll({
					scrollspeed: 60,
					mousescrollstep: 35,
					cursorwidth: 5,
					cursorborder: 0,
					cursorcolor: '#25272B',
					horizrailenabled: false
				});
			}
		);
		</script>
	<!--preloader-->
		<script type="text/javascript">
			$(window).load(function() {
				$("#status").fadeOut();
				$("#preloader").delay(350).fadeOut("slow");
			})
		</script>
	<!--make intro carousel height of window, carousel autoslide control and swipe-->
		<script>
		$(function(){
			$('#carousel_intro .item').css({'height':($(window).height())+'px'});
			$(window).resize(function(){
			$('#carousel_intro .item').css({'height':($(window).height())+'px'});
			});
			$('#carousel_intro, #carousel_content, #carousel_modal, #carousel_header_1, #carousel_header_3').carousel({interval: 0, pause: false})
		});
		</script>
		<script src="js/jquery.touchwipe.min.js"></script>
		<script type="text/javascript">
		jQuery(document).ready(function(){
			jQuery("#carousel_intro").touchwipe({
				wipeLeft: function() { jQuery("#carousel_intro").carousel('next'); },
				wipeRight: function() { jQuery("#carousel_intro").carousel('prev'); },
				min_move_x: 20,
				preventDefaultEvents: false
			});
			jQuery("#carousel_content").touchwipe({
				wipeLeft: function() { jQuery("#carousel_content").carousel('next'); },
				wipeRight: function() { jQuery("#carousel_content").carousel('prev'); },
				min_move_x: 20,
				preventDefaultEvents: false
			});
			jQuery("#carousel_modal").touchwipe({
				wipeLeft: function() { jQuery("#carousel_modal").carousel('next'); },
				wipeRight: function() { jQuery("#carousel_modal").carousel('prev'); },
				min_move_x: 20,
				preventDefaultEvents: false
			});
			jQuery("#carousel_header_1").touchwipe({
				wipeLeft: function() { jQuery("#carousel_header_1").carousel('next'); },
				wipeRight: function() { jQuery("#carousel_header_1").carousel('prev'); },
				min_move_x: 20,
				preventDefaultEvents: false
			});
			jQuery("#carousel_header_3").touchwipe({
				wipeLeft: function() { jQuery("#carousel_header_3").carousel('next'); },
				wipeRight: function() { jQuery("#carousel_header_3").carousel('prev'); },
				min_move_x: 20,
				preventDefaultEvents: false
			});
		});
		</script>
		<!--<script src="js/jquery.mobile.min.js"></script>
		<script>
		$(document).ready(function() {
			$("#carousel_intro").swiperight(function() {
				$("#carousel_intro").carousel('prev');
			});
				$("#carousel_intro").swipeleft(function() {
				$("#carousel_intro").carousel('next');
			});
		});
		$(document).ready(function() {
			$("#carousel_content").swiperight(function() {
				$("#carousel_content").carousel('prev');
			});
				$("#carousel_content").swipeleft(function() {
				$("##carousel_content").carousel('next');
			});
		});
		$(document).ready(function() {
			$("#carousel_modal").swiperight(function() {
				$("#carousel_modal").carousel('prev');
			});
				$("#carousel_modal").swipeleft(function() {
				$("#carousel_modal").carousel('next');
			});
		});
		$(document).ready(function() {
			$("#carousel_header_1").swiperight(function() {
				$("#carousel_header_1").carousel('prev');
			});
				$("#carousel_header_1").swipeleft(function() {
				$("#carousel_header_1").carousel('next');
			});
		});
		$(document).ready(function() {
			$("#carousel_header_3").swiperight(function() {
				$("#carousel_header_3").carousel('prev');
			});
				$("#carousel_header_3").swipeleft(function() {
				$("#carousel_header_3").carousel('next');
			});
		});
		</script>-->
	<!--parallax elements-->
		<script src="js/skrollr.js"></script>
		<!--[if lt IE 9]>
			<script type="text/javascript" src="js/skrollr.ie.min.js"></script>
		<![endif]-->
		<script type="text/javascript">
			$(document).ready(function() {
				$('.no-touch').length && skrollr.init({
					edgeStrategy: 'set',
					easing: {
						WTF: Math.random,
						inverted: function(p) {
						return 1-p;
						}
					},
					smoothScrolling: true,
					forceHeight: false
				});
			});
		</script>
	<!--google analytics-->
		<script type="text/javascript">
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'GOOGLE ANALYTICS CODE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!']);
			_gaq.push(['_trackPageview']);

			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
		</script>
	<!--contact form-->
		<script src="js/jquery.form.js"></script>
		<script type="text/javascript">
			$(document).ready(function() {
			var options = {
			target: '#form-alert',
			beforeSubmit: showRequest,
			success: showResponse
			};
			$('#contactForm').ajaxForm(options);
			});
			function showRequest(formData, jqForm, options) {
			var queryString = $.param(formData);
			return true;
			}
			function showResponse(responseText, statusText)	{
			}
			$.fn.clearForm = function() {
				return this.each(function() {
				var type = this.type, tag = this.tagName.toLowerCase();
				if (tag == 'form')
					return $(':input',this).clearForm();
				if (type == 'text' || type == 'password' || tag == 'textarea')
					this.value = '';
				else if (type == 'checkbox' || type == 'radio')
					this.checked = false;
				else if (tag == 'select')
					this.selectedIndex = -1;
				});
			};
		</script>
		<script src="js/jquery.promin.html"></script>
		<script>
		$('#contactForm').promin({
			'button': $('#next'),
			'labels': {
				'next': 'next',
				'submit': 'next'
				},
			events: {
				validate: function( fields ) {
					var empty = false;

					fields.each(function( i, e ) {
						var $e = $( e );
						var val = $e.val();
						var length = val.length;

						empty = ( length === 0 );

						// sound the alarms, abort mission, we have an empty field!
						if( empty ) {
							// show (first) invalid field and highlight
							$( '#contactForm' ).promin('show', i);
							$e.addClass( 'error' );

							return false;
						}
					});

					// if there are no empty fields, do submit
					return (!empty);
				}
			}
		});
		</script>
	<!--tour-->
		<script src="js/bootstrap.tour.min.html"></script>
		<script src="js/bootstrap.tour.cookie.html"></script>
	<!--	<script src="js/bootstrap.tour.steps.js"></script>-->
		<script>
		var $start, tour;
		$start = $("#start");
		tour = new Tour();
		tour.addSteps([
			{
				element: "#services",
				title: "services",
				content: "servicesservicesservicesservicesservicesservicesservices servicesservicesservicesservicesservicesservicesservices servicesservicesservicesservicesservicesservicesservices servicesservicesservicesservicesservicesservicesservices servicesservicesservicesservicesservicesservicesservices servicesservicesservicesservicesservicesservicesservices ",
				placement: "bottom"
			},
			{
				element: "#intro",
				title: "intro",
				content: "introintrointrointrointrointrointrointro introintrointrointrointrointrointrointro introintrointrointrointrointrointrointro introintrointrointrointrointrointrointro introintrointrointrointrointrointrointro introintrointrointrointrointrointrointro ",
				placement: "bottom"
			}
		]);
		tour.start();
		</script>
	<!--gallery-->
		<script src="js/toucheffects.js"></script>
		<script src="js/bigmodals.html"></script>
		<script>$('.modal').bigmodal('hide');</script>
	<!--menu close on select-->
		<script>
			$('.navbar a').click(function () { $(".nav-collapse").collapse("hide") });
		</script>
	<!--tooltip and popover trigger-->
		<script>
			$("[data-thumb=tooltip]").tooltip();
			$("[data-thumb=popover]").popover();
		</script>
	<!--if link points to nowhere don't go to top of page-->
		<script type="text/javascript">
			$('a[href="#"]').click(function(e) {
				return false;
			});
		</script>