<!--start contact section-->
<section id="contact">
    <div class="container">
        <div class="row margin">
            <div class="col-lg-8 col-sm-offset-2">
                <h1 class="text-center">Contatos</h1>
                <p class="text-center">Olá, se tiver alguma dúvida ou sugestão, entre em contato conosco.</p>
            </div>
            <div class="col-lg-6 col-sm-offset-3">
                <div class="row">
                    {{ form('class':'form-horizontal','role': 'form') }}
                        <div class="form-group">
                            <div class="col-sm-8 col-lg-8 col-sm-offset-2">
                                {{ content() }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputNome" class="col-sm-2 control-label">Nome:</label>
                            <div class="col-sm-8 col-lg-8">
                                {{ form.render('nome') }}
                                {{ form.messages('nome') }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail" class="col-sm-2 control-label">E-mail:</label>
                            <div class="col-sm-8 col-lg-8">
                                {{ form.render('email') }}
                                {{ form.messages('email') }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputMessage" class="col-sm-2 control-label">Mensagem:</label>
                            <div class="col-sm-8 col-lg-8">
                                {{ form.render('description') }}
                                {{ form.messages('description') }}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-8 col-lg-8">
                              {{ form.render('go') }}
                            </div>
                        </div>
                    {{endForm()}}
                </div>
            </div>
        </div>
    </div>
</section>
<!--end contact section-->
<!--start footer section-->
<section id="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-sm-6 margin">
                <p>2015 &copy; Incentiv Go</p>
            </div>
            <div class="col-lg-4 col-sm-6 col-sm-offset-2 margin social">
                <a class="facebook" href="http://www.facebook.com/incentivgo" target="_blank">Facebook</a> / 
                <a class="twitter" href="http://www.twitter.com/incentivgo" target="_blank">Twitter</a> 

            </div>
        </div>
    </div>
</section>
<!--end footer section-->
<!--start back to top button-->
<a href="#intro" class="hidden-sm go-top" data-0="opacity: 0;" data-1000="opacity: 1;">Início</a>
<!--end back to top button-->