<!--start intro section-->
<section id="intro">
    <div id="carousel_intro" class="carousel slide fadeing">
        <div class="carousel-inner">
            <div class="active item" id="slide_1" data-start="background-position: center 0px;" data-1440="background-position: center -250px;">
                <h1 data-start="opacity:1; top: 30%;" data-250="opacity: 0; top: 10%;"> Incentiv!!! Colaboradores incentivados, <p>gerando melhores resultados para sua empresa</p><p> Não fique de fora dessa</p></h1>
            </div>
        </div>
    </div>
    <div class="hidden-sm more">
        <a href="#services" class="btn btn-syndicate squared" data-start="opacity:1; margin-top: 0%;" data-250="opacity:0; margin-top: -10%;"><i class="icon-angle-down"></i> Saiba mais</a>
    </div>
</section>
<!--end intro section-->
<div class="rainbow"></div>
<!--start services section-->
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-sm-6 col-xs-12">
                <h1>Desafios</h1>
                <div class="col-lg-6 col-sm-6 margin">
                    <i class="icon-cogs red" data-bottom-center="opacity: 0;" data-bottom-bottom="opacity: 1;"></i>
                    <h3>Interaja</h3>
                    <h5>Lance desafios</h5>
                    <p><small>Lance desafios aos seus colaboradores e tenham resultados incríveis através de metas e incentivos</small></p>
                </div>
                <div class="col-lg-6 col-sm-6 margin">
                    <i class="icon-tablet yellow" data-bottom-center="opacity: 0;" data--60-bottom-bottom="opacity: 1;"></i>
                    <h3>Gamificação</h3>
                    <h5>Pontuações</h5>
                    <p><small>Gere pontuações aos seus colaboradores através desafios e tenha um crescimento acima do esperado</small></p>
                </div>
            </div>
            <div class="col-lg-6  col-sm-6 col-xs-12">
                <h1>Carreira</h1>
                 <div class="col-lg-6 col-sm-6 margin">
                    <i class="icon-eye-open green" data-bottom-center="opacity: 0;" data--120-bottom-bottom="opacity: 1;"></i>
                    <h3>Talentos</h3>
                    <h5>Acompanhe de perto</h5>
                    <p><small>Descubra pessoas capazes e crie grandes talentos dentro de sua empresa através de planos orientado a metas</small></p>
                </div>
                <div class="col-lg-6 col-sm-6 margin">
                    <i class="icon-eye-open green" data-bottom-center="opacity: 0;" data--120-bottom-bottom="opacity: 1;"></i>
                    <h3>Resultados</h3>
                    <h5>Tenha métricas</h5>
                    <p><small>Colaboradores mais engajados e antenados, gerando com isso, melhores resultados para sua empresa</small></p>
                </div>
            </div>
        </div>
    </div>
</section>
<!--start footer section-->
<section id="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-sm-6 margin copy">
                <p>2015 &copy; Incentiv Go</p>
            </div>
            <div class="col-lg-4 col-sm-6 col-sm-offset-2 margin social">
                <a class="facebook" href="http://www.facebook.com/incentivgo" target="_blank">Facebook</a> / 
                <a class="twitter" href="http://www.twitter.com/incentivgo" target="_blank">Twitter</a> / 
                <a class="google" href="https://plus.google.com/u/0/104533843132286032110/posts" target="_blank">Google+</a>
            </div>
        </div>
    </div>
</section>
<!--end footer section-->
<!--start back to top button-->
<a href="#intro" class="hidden-sm go-top" data-0="opacity: 0;" data-1000="opacity: 1;">Início</a>
<!--end back to top button-->