
<section id="content">
    <section class="main padder">
        <div class="clearfix">
            <h4><i class="fa fa-edit"></i>Ideias</h4>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <!-- .breadcrumb -->
                <ul class="breadcrumb">
                    <li><a href="#">Ideias</a></li>
                </ul>
                <!-- / .breadcrumb -->
            </div>
            <div class="col-lg-10 col-lg-offset-1" id="mensagem-modal-ideia"><?php echo $this->flashSession->output(); ?></div>
            <div class="col-lg-10 col-lg-offset-1">
                <!-- scrollable inbox widget -->
                <section class="panel">
                    <header class="panel-heading">
                        <div class="pull-left">
                            <button type="button" class="btn btn-sm btn-white squared" id="btnCriarIdeia" >Cadastrar Ideia</button>
                        </div>
                        <div class="col-sm-4 col-lg-offset-3">
                            <div class="input-group">
                                <input type="text" id="filterIdeias" class="input-sm form-control" placeholder="Pesquisar por ideias">
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-sm btn-white" id="btnPesquisarIdeias">Pesquisar</button>
                                </span>
                            </div>
                        </div>
                        <div class="pull-right">
                            <span class="label label-large bg-default" id="quantidade-ideia" data-placement="left" data-toggle="tooltip" data-original-title="Ideias Cadastradas">0</span> Ideias 
                        </div>
                    </header>
                    <div id="pesquisarIdeia"></div>
                </section>
            </div>
    </section>
</section>
<!-- Início Modal Criar Ideia -->
<div class="modal fade" id="modalCriarIdeia" tabindex="-5" role="dialog" aria-labelledby="modalCriarIdeiaLabel" aria-hidden="true">
   {{ form('empresa/ideia/salvar-ideia', 'class':'form-horizontal', 'id':'form-ideia', 'method': 'post') }}
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                    <h4 class="modal-title" id="myModalLabel"></h4>
                </div>
                <div class="modal-body" id="modal-body-ideia"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-default squared" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-sm btn-syndicate squared">Salvar ideia</button>
                </div>
            </div>
        </div>
   {{endForm()}}
</div>
<!-- Fim Modal Cadastro ideia -->
{{ javascript_include('js/empresa/ideia/ideia.js') }}
<script type="text/javascript">  
    $(document).ready(function(){
        Ideia.init();
    });   
</script>