{{hidden_field("dados[id]",'value':id,'id':'hidden_id')}}
<section class="main padder">
    <div class="row">
        <div class="col-sm-12">
            <div class="form-group">
                <label class="col-lg-5 control-label" data-placement="left" data-toggle="tooltip" data-original-title="{{lang['pontuacao_dada_enviar']}}">{{lang['ideia_enviada']}}:</label>
                <div class="col-lg-7">
                    <div class="spinner input-group col-lg-3 form-control-static" id="MySpinner">
                        {{ text_field("dados[pontuacao_ideia_enviada]", 'id':'ideia-enviada','value':pontuacao_ideia_enviada, 'class':'input-sm spinner-input form-control') }}
                        <div class="btn-group btn-group-vertical input-group-btn">
                            <button class="btn btn-white spinner-up" type="button">
                                <i class="fa fa-chevron-up"></i>
                            </button>
                            <button class="btn btn-white spinner-down" type="button">
                                <i class="fa fa-chevron-down"></i>
                            </button>
                        </div>
                    </div>
                     <label id="ideia-error" class="error" style="display: none;" for="ideia-enviada">{{lang['campo_obrigatorio']}}</label>
                </div>   
            </div>
            <div class="form-group">
                <label class="col-lg-5 control-label" data-placement="left" data-toggle="tooltip" data-original-title="{{lang['pontuacao_dada_aprovada']}}" >{{lang['ideia_aprovada']}}:</label>
                <div class="col-lg-7">
                    <div class="spinner input-group col-lg-3 form-control-static" id="MySpinner">
                        {{ text_field("dados[pontuacao_ideia_aprovada]", 'id':'ideia-aprovada','value':pontuacao_ideia_aprovada, 'class':'input-sm spinner-input form-control') }}
                        <div class="btn-group btn-group-vertical input-group-btn">
                            <button class="btn btn-white spinner-up" type="button">
                                <i class="fa fa-chevron-up"></i>
                            </button>
                            <button class="btn btn-white spinner-down" type="button">
                                <i class="fa fa-chevron-down"></i>
                            </button>
                        </div>
                    </div>
                     <label id="ideia-error" class="error" style="display: none;" for="ideia-aprovada">{{lang['campo_obrigatorio']}}</label>
                </div>   
            </div>
        </div>
    </div>
</section>
{{hidden_field("lang",'value':lang['lang'])}}
{{ javascript_include('js/empresa/ideia/mapear-pontuacao.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        ModalMapearPontuacao.init($("#lang").val());
    });
</script>