{{hidden_field("id",'value':id)}}
{{hidden_field("resposta",'value':'')}}
<section class="main padder">
    <div class="row">
        <div class="col-sm-11">
            
            <div class="form-group" data-placement="left" data-toggle="tooltip" title="{{lang['colaborador_enviou_ideia']}}">
                <label class="col-lg-3 control-label">{{lang['p_colaborador']}}:</label>
                <div class="col-lg-9">
                   <p class="form-control-static">{{colaborador}}</p>
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-lg-3 control-label">{{lang['titulo']}}:</label>
                <div class="col-lg-9">
                   <p class="form-control-static">{{titulo}}</p>
                </div>
            </div>
            
            <div class="form-group" data-placement="left" data-toggle="tooltip" title="{{lang['descricao_ideia']}}">
                <label class="col-lg-3 control-label">{{lang['descricao']}}:</label>
                <div class="col-lg-9">
                   <p class="form-control-static">{{descricao}}</p>
                </div>
            </div>
            
            <div class="form-group" data-placement="left" data-toggle="tooltip" title="{{lang['data_de_envio_empresa']}}">
                <label class="col-lg-3 control-label">{{lang['data_de_envio']}}:</label>
                <div class="col-lg-4">
                    <p class="form-control-static">
                        {% if(lang['lang'] == 'en') %}
                            {{ date('m/d/Y', dt_envio) }}
                        {% else %}
                            {{ date('d/m/Y', dt_envio) }}
                        {% endif %}
                    </p>
                </div>   
            </div>
        </div>
    </div>
</section>
{{ javascript_include('js/empresa/ideia/modal-ideia.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        ModalIdeia.init();
    });
</script>