{{hidden_field("dados[id]",'value':id)}}
<section class="main padder">
    <div class="row">
        <div class="col-sm-11">
            
            <div class="form-group">
                <label class="col-lg-4 control-label">{{lang['recompensa']}}</label>
                <div class="col-lg-8">
                    {{ text_area("dados[recompensa]", 'id':'recompensa', 'placeholder': 'Ex:'~lang['tirar_dia_folga'],'value':recompensa,'rows':'3', 'class':'bg-focus form-control') }}
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-4 control-label">{{lang['pontuacao_debitada']}}</label>
                <div class="col-lg-8">
                    <div class="spinner input-group col-lg-3" id="MySpinner">
                        {{ text_field("dados[pontuacao]", 'id':'pontuacao','value':pontuacao, 'class':'input-sm spinner-input form-control') }}
                        <div class="btn-group btn-group-vertical input-group-btn">
                            <button class="btn btn-white spinner-up" type="button">
                                <i class="fa fa-chevron-up"></i>
                            </button>
                            <button class="btn btn-white spinner-down" type="button">
                                <i class="fa fa-chevron-down"></i>
                            </button>
                        </div>
                    </div>
                     <label id="pontuacao-error" class="error" style="display: none;" for="pontuacao">{{lang['campo_obrigatorio']}}</label>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-4 control-label">{{lang['observacao']}}</label>
                <div class="col-lg-8">
                    {{ text_area("dados[observacao]", 'id':'observacao', 'placeholder': lang['observacoes'],'value':observacao,'rows':'3', 'class':'bg-focus form-control') }}
                </div>
            </div>
        </div>
    </div>
    {{hidden_field("lang",'value':lang['lang'])}}
</section>
<!-- Fim Modal Criar Recompensa -->
{{ javascript_include('js/empresa/recompensa/modal-recompensa.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        ModalRecompensa.init($("#lang").val());
    });
</script>

