<tbody>
    <tr>
        <td style="padding:40px 0  0 0;">
            <p style="color:#000;font-size: 16px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;font-weight:normal;">

            <h2 style="font-size: 14px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">Você está quase lá! Apenas Confirme seu e-mail</h2>

            <p style="font-size: 13px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">Você criou com sucesso uma conta no Incentiv Educ. Para ativá-la, clique abaixo para verificar o seu endereço de e-mail.

                <br>
                <br>
                <a style="background:#E86537;color:#fff;padding:10px" href="http://{{ publicUrl }}{{ confirmUrl }}">Confirmar</a>

                <br>
                <br>
                Incentiv Educ
                <br>
            </p>
        </td>
    </tr>
</tbody>