<section class=" tasks-widget">
        <div class="task-content">
            <div id="mensagem-modal-resposta-ajudas"><?php echo $this->flashSession->output(); ?></div>
            <ul class="task-list ui-sortable-modal ul-ajudas" id="sortable" >
                {% for ajuda in ajudas %}
                <li class="list-primary" id="li_ajuda_{{ajuda['id']}}">
                    <div class="task-title">
                        <span class="task-title-sp">{{ajuda['mensagem']}}</span>
                        <!--<span class="badge bg-primary">+ 10 incentivs </span>-->
                    </div><br/>
                    <div class="task-title pull-left">
                        <span class="sp-title moment">{{ajuda['envioDt']}}</span>
                    </div>
                    <div id={{ajuda['id']}} class="task-title center">
                        {{lang['respostas']}} ({{ajuda['count_respostas']}})
                    </div>
                    {% if(ajuda['ativo'] == 'Y') %}
                        <div id={{ajuda['id']}} class="task-title pull-right">
                            {% if(ajuda['usuarioId'] != usuarioId) %}
                                <button type="button" id="btnAjudar" class="btn btn-xs btn-facebook btnAjudar">{{lang['ajudar']}}</button>
                            {% else %}
                                {% if( ajuda['count_respostas'] > 0 ) %}
                                    <button type="button" id="btnVerAjudas" class="btn btn-xs btn-theme btnAjudar">{{lang['ver_resposta']}}(s)</button>
                                {% endif %}
                                <button type="button" class="btn btn-xs btn-theme04 btnExcluirAjuda">{{lang['excluir']}}</button>
                            {% endif %}   
                        </div>
                    {% endif %}
                </li>
                <li class="list-primary" id="li_motivo_{{ajuda['id']}}" style="display: none">
                    <div class="task-title inline"> 
                        <form role="form" class="form-cadastro" id="form_ajuda_{{ajuda['id']}}">
                             <div>
                                 <textarea id="txt_motivo_{{ajuda['id']}}" placeholder="{{lang['informe_motivo_ajuda']}}" class="form-control"></textarea>
                            </div>
                       </form>
                    </div><br/>
                    <div id="{{ajuda['id']}}" class="task-title pull-right">
                        <button type="button" id="btnEnviarMotivoDescarte" class="btn btn-xs btn-facebook">{{lang['enviar']}}</button>
                        <button type="button" id="btnCancelarDescarte" class="btn btn-xs btn-theme btnCancelarDescarte">{{lang['cancelar']}}</button>
                    </div>
                </li>
                {% elsefor %}
                <li class="list-primary text-center">
                    <div class="task-title">
                        <span class="task-title-sp">{{lang['nenhuma_ajuda_momento']}}</span>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <ul class="task-list ui-sortable-modal" id="ul_ajuda" style="display: none">
                <li class="list-primary" >
                    <div class="task-title inline"> 
                        <form role="form" class="form-ajuda" id="form_ajuda">
                             <div>
                                 <textarea id="txt_mensagem_ajuda" name="txt_mensagem_ajuda" placeholder="{{lang['informe_duvida_colega']}}" class="form-control"></textarea>
                            </div>
                       </form>
                    </div><br/>
                    <div class="task-title pull-right">
                        <button type="button" id="btnEnviarAjuda" class="btn btn-xs btn-facebook">{{lang['enviar']}}</button>
                        <button type="button" id="btnCancelarAjuda" class="btn btn-xs btn-default">{{lang['cancelar']}}</button>
                    </div>
                </li>
            </ul>
    </div>
     {{hidden_field("lang",'value':lang['lang'])}}
</section>
<!-- Fim Modal Cadastro colaborador -->
{{ javascript_include('js/colaborador/ajuda/modal-ajudas.js') }}
<script type="text/javascript">  
    $(document).ready(function(){
        ModalAjudas.init($("#lang").val());
    });   
</script>