<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"> 
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="description" content="Programa de incentivo a colaboradores de empresas" />
        <meta name="author" content="André Maciel Fagundes">
        <meta name="keywords" content="incentivo, empresas, business, corporações, corporation"/>
        <meta name="robots" content="index,follow,noodp,noydir" />
        <title>{{lang['bem_vindo']}}</title>

        <link rel="canonical" href="http://www.incentiv.com.br/" />
        <link rel="shortcut icon" href="" />
        
        {{ javascript_include('js/modernizr.js') }}
        <!-- Le styles -->
        {{ stylesheet_link('css/bootstrap/bootstrap.min.css') }}
        
        {{ stylesheet_link('css/fonts/font.css') }}
        {{ stylesheet_link('css/fonts/font-awesome.min.css') }}
        {{ stylesheet_link('css/empresa/select2.css') }}
        {{ stylesheet_link('css/empresa/plugin.css') }}
        
        {{ stylesheet_link('http://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css', false) }}
<!--        {{ stylesheet_link('http://fonts.googleapis.com/css?family=Raleway:200,400', false) }}-->
        
        {{ javascript_include('js/jquery.min.js') }}
        {{ javascript_include('js/bootstrap.min.js') }}
        <!--[if lt IE 9]>
            {{ javascript_include('js/empresa/js-library/ie/respond.min.js') }}
            {{ javascript_include('js/empresa/js-library/ie/html5.js') }}
            {{ javascript_include('js/empresa/js-library/ie/excanvas.js') }}
        <![endif]-->
        <!--[if lte IE 8]>
                {{ javascript_include('js/empresa/js-library/ie/respond.min.js') }}
	<![endif]-->
    </head>

    <body  data-spy="scroll" data-target=".navbar" data-offset='61' >
       
        {{ content() }} 

    </body>
</html>