<!--start intro section-->
<section id="intro">
    <div id="carousel_intro" class="carousel slide fadeing">
        <div class="carousel-inner">
            <div class="active item" id="slide_1" data-start="background-position: center 0px;" data-1440="background-position: center -250px;">
                <h1 data-start="opacity:1; top: 40%;" data-250="opacity: 0; top: 10%;"> Incentiv!!! Exclusivo para você que é aluno<p> de uma universidade, faculdade ou escola particular</p></h1>
            </div>
        </div>
    </div>
    <div class="hidden-sm more">
        <a href="#services" class="btn btn-syndicate squared" data-start="opacity:1; margin-top: 0%;" data-250="opacity:0; margin-top: -10%;"><i class="icon-angle-down"></i> Saiba mais</a>
    </div>
</section>
<!--end intro section-->
<div class="rainbow"></div>
<!--start services section-->
<section id="services">
    <div class="container">
        <div class="row">
            <div class=" col-lg-6">
                <h1>Alunos</h1>
            </div>
            <div class="col-lg-6">
                <h1>Instituições</h1>
            </div>
            <div class="col-lg-3 col-sm-3 margin">
                <i class="icon-cogs red" data-bottom-center="opacity: 0;" data-bottom-bottom="opacity: 1;"></i>
                <h3>Interaja</h3>
                <h5>Seja o nerd, ops. O melhor da sua instituição</h5>
                <p><small>Se sua instituição está no Incentiv, parabéns, você pode se cadastrar e participar do programa de incentivo, uhuuuuu!!!</small></p>
            </div>
            <div class="col-lg-3 col-sm-3 margin">
                <i class="icon-tablet yellow" data-bottom-center="opacity: 0;" data--60-bottom-bottom="opacity: 1;"></i>
                <h3>Ganhe prêmios incríveis</h3>
                <h5>Fique por dentro de tudo e ganhe pontos</h5>
                <p><small>No final do semestre os melhores alunos serão presenteados pela instituição</small></p>
            </div>
            <div class="col-lg-3 col-sm-3 margin">
                <i class="icon-eye-open green" data-bottom-center="opacity: 0;" data--120-bottom-bottom="opacity: 1;"></i>
                <h3>Campanha de incentivo</h3>
                <h5>Lance a campanha de incentivo de sua instituição</h5>
                <p><small>Tenha alunos mais antenados e empolgados com sua vida acadêmica</small></p>
            </div>
            <div class="col-lg-3 col-sm-3 margin">
                <i class="icon-eye-open green" data-bottom-center="opacity: 0;" data--120-bottom-bottom="opacity: 1;"></i>
                <h3>Campanhas de sucesso</h3>
                <h5>Clientes exclusivos</h5>
                <p><small>Tenha campanhas promocionais altamente qualificadas</small></p>
            </div>
        </div>
    </div>
</section>
<!--start footer section-->
<section id="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-sm-6 margin copy">
                <p>2014 &copy; Incentiv</p>
            </div>
            <div class="col-lg-4 col-sm-6 col-offset-2 margin social">
                <a class="facebook" href="http://www.facebook.com/awerest" target="_blank">Facebook</a> / 
                <a class="twitter" href="http://www.twitter.com/awerest" target="_blank">Twitter</a> / 
                <a class="google" href="https://plus.google.com/u/0/104533843132286032110/posts" target="_blank">Google+</a>
            </div>
        </div>
    </div>
</section>
<!--end footer section-->
<!--start back to top button-->
<a href="#intro" class="hidden-sm go-top" data-0="opacity: 0;" data-1000="opacity: 1;">Go Top</a>
<!--end back to top button-->