<section class="main padder">
    <div class="col-sm-12">
        <div class="form-group">
            <div class="col-lg-12">
                <p class="form-control-static text-center"><strong>{{noticia.titulo}}</strong></p>
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-12">
                <p class="form-control-static">{{noticia.noticia}}</p>
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-12">
                <p class="form-control-static">{{lang['enviada_em']}}:
                    {% if(lang['lang'] == 'pt-BR') %}
                        {{ date('d/m/Y', noticia.criacaoDt) }}
                    {% else %}
                        {{ date('m/d/Y', noticia.criacaoDt) }}
                    {% endif %}
                </p>
                <div class="task-title pull-right">
            <button type="button" id="btnVoltarNoticia" class="btn btn-xs btn-default">{{lang['voltar']}}</button>
        </div>
            </div>   
        
        </div>
        
    </div>
</section>
<!-- Fim Modal Cadastro colaborador -->
{{ javascript_include('js/colaborador/noticia/modal-ler-noticia.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        ModalLerNoticia.init();
    });
</script>