<section class=" tasks-widget">
        <div class="task-content">
            <ul class="task-list ui-sortable-modal ul-noticias" id="sortable" >
                {% for noticia in noticias %}
                <li class="list-primary">
                    <div class="task-title">
                        <span class="task-title-sp">{{noticia.titulo}}</span>
                    </div><br/>
                    <div class="task-title pull-left">
                        <label>{{lang['enviada_em']}}:</label> 
                        {% if(lang['lang'] == 'pt-BR') %}
                            {{ date('d/m/Y', noticia.criacaoDt) }}
                        {% else %}
                            {{ date('m/d/Y', noticia.criacaoDt) }}
                        {% endif %}
                    </div>
                    <div class="task-title pull-right">
                        <button type="button" id="{{noticia.id}}" class="btn btn-xs btn-facebook btnLerNoticia">{{lang['ler_noticia']}}</button>
                    </div>
                </li>
                {% elsefor %}
                <li class="list-primary text-center">
                    <div class="task-title">
                        <span class="task-title-sp">{{lang['nenhuma_noticia_momento']}}</span>
                    </div>
                </li>
                {% endfor %}
            </ul>
    </div>
</section>
<!-- Fim Modal Cadastro colaborador -->
{{ javascript_include('js/colaborador/noticia/modal-noticias.js') }}
<script type="text/javascript">  
    $(document).ready(function(){
        ModalNoticias.init();
    });   
</script>