<section class="main padder">
    <div class="col-sm-12">
        <div class="form-group">
            <div class="col-lg-12">
                <p class="form-control-static text-center"><strong>{{noticia.titulo}}</strong></p>
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-12">
                <p class="form-control-static">{{noticia.noticia}}</p>
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-12">
                <p class="form-control-static">Enviada em: {{ date('d/m/Y', noticia.criacaoDt) }}</p>
                <div class="task-title pull-right">
            <button type="button" id="btnVoltarNoticia" class="btn btn-xs btn-theme">Voltar</button>
        </div>
            </div>   
        
        </div>
        
    </div>
</section>
<!-- Fim Modal Cadastro colaborador -->
{{ javascript_include('js/colaborador/noticia/modal-ler-noticia.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        ModalLerNoticia.init();
    });
</script>