
<table class="table table-responsive text-small">
    <tbody>
        {% for campanha in page.items %}
            <tr class="row">
                <td class="td-responsive">
                    <div class="pull-right text-muted">
                        <strong class="h3 text-info text-center">{{campanha.pontuacao}}</strong> pts<br>
                        <small>
                            {% if(campanha.ativo == 'N') %}
                            {% set status = 'danger' %} 
                            {% set status_label = 'Inativo' %}
                            {% else  %}
                            {% set status = 'success' %} 
                            {% set status_label = 'Ativo' %}
                            {% endif %}
                            <span class="label label-{{status}}">
                                {{status_label}}
                            </span>
                        </small>
                    </div>
                    <a href="#">{{campanha.inicioDt}} a {{campanha.fimDt}} </a> 
                    <div class="btn-group">
                        <button class="dropdown-toggle" role="button" data-toggle="dropdown"><i class="fa fa-gear"></i></button>
                        <ul class="dropdown-menu pull-left">
                            {% if(campanha.ativo == 'N') %}
                            <li class="text-left">{{linkTo('empresa/ativar-inativar-desafio/ativo/Y/id/'~campanha.id, '<i class="icon-plus-sign"></i> Ativar')}}
                                {% else %}
                            <li class="text-left">{{linkTo('empresa/ativar-inativar-desafio/ativo/N/id/'~campanha.id, '<i class="fa fa-minus-square-o"></i> Inativar')}}</li>
                                {% endif %}
                                <li class="text-left"><a href="#" class="btnAlterar" id="{{campanha.id}}"><i class="icon-pencil"></i> Alterar</a></li>
                            <li class="divider"></li>
                            <li class="text-left"><a href="#" id="btnDeletar_{{campanha.id}}"><i class="icon-remove"></i> Deletar</a> </li>
                        </ul>
                    </div>
                    <h6>{{campanha.desafio}}</h6>
                </td>
            </tr>
        {% elsefor %}
            <tr class="row">
                <td class="table-responsive">
                    <h6 class="text-center text-info">Nenhum desafio cadastrado.</h6>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<section class="panel-footer">
    <footer>
        <div class="row">
            <div class="col-sm-4 col-sm-offset-3 text-center">
                <small class="text-muted inline m-t-small m-b-small">Mostrando {{ page.current }} de {{ page.total_pages }}</small>
            </div>
            <div class="col-sm-5 text-right text-center-sm">                
                <ul class="pagination pagination-small m-t-none m-b-none">
                    <li><a href="#" class="fa btnPaginacaoDesafio" id="1"><i class="icons icon-fast-backward"></i> Primeiro</a></li>
                    <li><a href="#" class="fa btnPaginacaoDesafio" id="{{page.before}}"><i class="icons icon-step-backward"></i> Anterior</a></li>
                    <li><a href="#" class="fa btnPaginacaoDesafio" id="{{page.next}}"><i class="icons icon-step-forward"></i> Próximo</a></li>
                    <li><a href="#" class="fa btnPaginacaoDesafio" id="{{page.last}}">Último <i class="icons icon-fast-forward"></i> </a></li>
                </ul>
                {{hidden_field("quantDesafio","value":page.total_items )}}
            </div>
        </div>
    </footer>
</section>
{{ javascript_include('js/empresa/desafio/pesquisar-desafio.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        pesquisarDesafio.init();
    });
</script>