{{ content() }}
<section id="contact">
    <div class="container">
        <div class="row margin">
            <div class="jumbotron">
                <h1>Erro interno</h1>
                <p>Algo deu errado, se o erro continuar, por favor entre em contato conosco</p>
                <p>{{ link_to('/', 'Início', 'class': 'btn btn-primary') }}</p>
            </div>
        </div>
    </div>
</section>