{{ content() }}
<section id="contact">
    <div class="container">
        <div class="row margin">
            <div class="jumbotron">
                <h1>Não autorizado</h1>
                <p>Você não tem acesso a esta opção. Contate um administrador</p>
                <p>{{ link_to('index', 'Início', 'class': 'btn btn-primary') }}</p>
            </div>
        </div>
    </div>
</section>