<section id="container" >
    <!-- **********************************************************************************************************************************************************
    TOP BAR CONTENT & NOTIFICATIONS
    *********************************************************************************************************************************************************** -->
    <!--header start-->
    <header class="header black-bg">
        <div class="sidebar-toggle-box">
            <div class="fa fa-bars tooltips" data-placement="right" data-original-title="<> Menu"></div>
        </div>
        <!--logo start-->
        {{ link_to('colaborador', '<span>Incentiv Go</span>','class':'logo') }}
        <!--logo end-->
        <div class="nav notify-row" id="top_menu">
            <!--  notification start -->
            <ul class="nav top-menu">
                <!-- inbox dropdown start-->
                <li id="header_inbox_bar" class="dropdown">
                    
                    <a data-toggle="dropdown" class="dropdown-toggle" href="index.html#">
                        <i class="fa fa-envelope-o"></i>
                        <span class="badge bg-danger count-n">0</span>
                    </a>
                    <ul class="dropdown-menu extended inbox">
                        <div class="notify-arrow notify-arrow-green"></div>
                        <li>
                            <p class="green">Você possui <span class="count-n">0</span> mensagens</p>
                        </li>
                        <li>
                            {{ link_to('colaborador/mensagens', 'Mostrar todas as mensagens') }}
                        </li>
                    </ul>
                </li>
                <!-- inbox dropdown end -->
            </ul>
            <!--  notification end -->
        </div>
        <div class="top-menu">
            <ul class="nav pull-right top-menu">
                <li>{{ link_to('session/logout', 'Sair','class':'logout') }}</li>
            </ul>
        </div>
    </header>
    <!--header end-->

    <!-- **********************************************************************************************************************************************************
    MAIN SIDEBAR MENU
    *********************************************************************************************************************************************************** -->
    <!--sidebar start-->
    <aside>
        <div id="sidebar"  class="nav-collapse ">
            <!-- sidebar menu start-->
            <ul class="sidebar-menu" id="nav-accordion">
                {% if( avatar is empty ) %}
                    {% set avatar_user = 'bfdc40e956b123b24b4962cc9409485a.jpg' %} 
                {% else  %}
                    {% set avatar_user = empresaId~'/'~id~'/'~'60_'~avatar %} 
                {% endif %}
                <p class="centered">{{ link_to('colaborador/perfil', image( 'img/users/'~avatar_user,'class':'img-circle','width':'60px')) }}</p>
                <h5 class="centered">{{usuario_logado}}</h5>

                <li class="mt">
                    <!--<a href="#" class="active btnBody" id="geral"><i class="fa fa-dashboard"></i><span>Geral</span></a>-->
                    {{ link_to('colaborador', '<i class="fa fa-dashboard"></i><span>Geral</span>','class':'active') }}
                </li>

                <li class="sub-menu">
                    <!--<a href="#" class="btnBody" id="ideia"><i class="fa fa-dashboard"></i><span>Ideias</span></a>-->
                    {{ link_to('colaborador/ideia', '<i class="li_bulb"></i><span>Ideias</span>') }}
                </li>

<!--                <li class="sub-menu">
                    <a href="javascript:;" >
                        <i class="fa fa-desktop"></i>
                        <span>Metas</span>
                    </a>
                    <ul class="sub">
                        <li>{{ link_to('colaborador/metas/1', 'Profissionais') }}</li>
                        <li>{{ link_to('colaborador/metas/2', 'Pessoais') }}</li>
                    </ul>
                </li>-->

                <li class="sub-menu">
                    {{ link_to('colaborador/perfil', '<i class="fa fa-cogs"></i><span>Perfil</span>') }}
                </li>
                 <li class="sub-menu" id="menu-mensagem">
                     {{ link_to("colaborador/mensagens", 'data-toggle':'tooltip','data-placement':'top','data-original-title':'Todas as mensagens', '<i class="fa fa-envelope-o fa-lg"></i><span>Mensagens</span>') }}
                </li>
            </ul>
            <!-- sidebar menu end-->
        </div>
    </aside>
    <!--sidebar end-->

    <section id="main-content">
        <section class="wrapper">
            <div class="row mt">
                <div id="div-body">{{ content() }}</div>
                    <!-- USUARIOS DO CHAT -->
                <div id="div-chat"></div>
                    <!-- FIM USUARIOS DO CHAT -->
            </div>

        </section>
    </section>
    <div class="chat-window-container"></div>
</section>
<script type="text/javascript" src="http://localhost:8088/socket.io/socket.io.js"></script>
{{ javascript_include('js/colaborador/layout/private-colaborador.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        PrivateColaborador.init();
    });
</script>
