{{ content() }}
<section id="contact">
    <div class="container">
        <div class="row margin">
            <div class="jumbotron">
                <div class="jumbotron">
                    <h1>Página não encontrada</h1>
                    <p>Desculpe, você acessou uma página que não existe ou foi movida</p>
                    <p>{{ link_to('index', 'Início', 'class': 'btn btn-primary') }}</p>
                </div>
            </div>
        </div>
</section>