<html>
    <head></head>
    <body style="background-color: #E4E4E4;padding: 20px; margin: 0; min-width: 640px;">
        <table border="0" cellspacing="0" width="530" style="color:#262626;background-color:#fff;
               padding:27px 30px 20px 30px;margin:auto; border:1px solid #e1e1e1;">
            <tbody>
                <!-- header -->
                <tr style="background:#D44413">
                    <td style="padding-left:20px">
                        <a target="_blank" style="text-decoration:none;color:inherit;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;font-weight:normal;">
                            <h1 style="color:#fff">Incentiv Go</h1>
                        </a>
                    </td>
                </tr>
            </tbody>

            {{ content() }}

        </table>
    </body>
</html>