<!-- header -->
<header id="header" class="navbar">
    <ul class="nav navbar-nav navbar-avatar pull-right">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">            
                <span class="hidden-xs-only">{{usuario_logado}}</span>
                <span class="thumb-small avatar inline">{{image( 'img/'~avatar, 'class':'img-circle', 'alt':'Universidade IESB') }}</span>
                <b class="caret hidden-xs-only"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="#">Perfil</a></li>
                <li><a href="#"><span class="badge bg-danger pull-right">3</span>Notificações</a></li>
                <li class="divider"></li>
                <!--<li><a href="docs.html">Ajuda</a></li>-->
                <li>{{ link_to('session/logout', 'Sair') }}</li>
            </ul>
        </li>
    </ul>
    <a class="navbar-brand" href="#">Incentiv</a>
    <button type="button" class="btn btn-link pull-left nav-toggle visible-xs" data-toggle="class:slide-nav slide-nav-left" data-target="body">
        <i class="fa fa-bars fa-lg text-default"></i>
    </button>
    <ul class="nav navbar-nav hidden-xs">
        <li>
            <div class="m-t m-b-small" id="panel-notifications">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-comment-o fa-fw fa-lg text-default"></i><b class="badge badge-notes bg-danger count-n">2</b></a>
                <section class="dropdown-menu m-l-small m-t-mini">
                    <section class="panel panel-large arrow arrow-top">
                        <header class="panel-heading bg-white"><span class="h5"><strong>Você tem <span class="count-n">2</span> notificações</strong></span></header>
                        <div class="list-group">
                            <a href="#" class="media list-group-item">
                                <span class="pull-left avatar thumb-small">{{image( 'img/avatar.jpg', 'class':'img-circle', 'alt':'John said') }}</span>
                                <span class="media-body block m-b-none">
                                    Moved to Bootstrap 3.0<br>
                                    <small class="text-muted">23 June 13</small>
                                </span>
                            </a>
                            <a href="#" class="media list-group-item">
                                <span class="media-body block m-b-none">
                                    Adicionado um evento<br>
                                    <small class="text-muted">Início: 19 Abril 2014</small>
                                </span>
                            </a>
                        </div>
                        <footer class="panel-footer text-small">
                            <a href="#" class="pull-right"><i class="fa fa-cog"></i></a>
                            <a href="#">Mostrar todas as notificações</a>
                        </footer>
                    </section>
                </section>
            </div>
        </li>
    </ul>
    {{ form(null, 'class':'navbar-form pull-left shift', 'data-toggle':'shift:appendTo','data-target':'.nav-primary') }}
        <i class="fa fa-search text-muted"></i>
        <input type="text" class="input-sm form-control col-lg-6" placeholder="Colaboradores">
    {{endForm()}}
</header>
<!-- / header -->
<!-- nav vertical -->
<nav id="nav" class="nav-primary hidden-xs nav-vertical">
    <ul class="nav" data-spy="affix" data-offset-top="50">
        <li class=" active dropdown-submenu">
            {{ link_to("empresa", '<i class="fa fa-th fa-lg"></i><span>Geral</span>') }}
        </li>
        <li class="dropdown-submenu">
            {{ link_to("empresa/desafio",'alt':'Gere desafios aos seus colaboradores','title':'Gere desafios aos seus colaboradores',  '<i class="fa fa-arrow-circle-right"></i><span>Desafios</span>') }}
        </li>
        <li class="dropdown-submenu">
            {{ link_to("empresa/noticia",'alt':'Informe as novidades da empresa pra seus colaboradores','title':'Informe as novidades da empresa pra seus colaboradores', '<i class="fa fa-arrow-circle-right"></i><span>Notícias</span>') }}
        </li>
<!--        <li class="dropdown-submenu">
            {{ link_to("empresa/regra", '<i class="fa fa-arrow-circle-right"></i><span>Regras</span>') }}
        </li>-->
        <li>
            {{ link_to("empresa/colaborador",'alt':'Cadastro e alteração dos usuários','title':'Cadastro e alteração dos usuários',  '<i class="fa fa-edit fa-lg"></i><span>Usuários</span>') }}
        </li>
        <li>
            {{ link_to("empresa/ideia", 'alt':'Ideias enviadas pelos colaboradores','title':'Ideias enviadas pelos colaboradores', '<i class="fa fa-edit fa-lg"></i><span>Banco de ideias</span>') }}
        </li>
<!--        <li>
            {{ link_to("empresa/pontuacao", '<i class="fa fa-edit fa-lg"></i><span>Pontuação</span>') }}
        </li>-->
<!--        <li class="dropdown-submenu">
            <a href="#"><i class="fa fa-calendar fa-lg"></i><span>Eventos</span></a>
            <ul class="dropdown-menu">
                <li>{{ link_to("empresa/evento/1", 'Palestras') }}</li>
                <li>{{ link_to("empresa/evento/2", 'Outros') }}</li>
            </ul>
        </li>-->
    </ul>
</nav>
{{ content() }}
<!-- footer -->
  <footer id="footer">
    <div class="text-center padder clearfix">
      <p>
        <small>&copy; 2014, Redes sociais do Incentiv Educ</small><br><br>
        <a href="#" class="btn btn-xs btn-circle btn-twitter"><i class="fa fa-twitter"></i></a>
        <a href="#" class="btn btn-xs btn-circle btn-facebook"><i class="fa fa-facebook"></i></a>
        <a href="#" class="btn btn-xs btn-circle btn-gplus"><i class="fa fa-google-plus"></i></a>
      </p>
    </div>
  </footer>
  <!-- / footer -->