<!-- header -->
<header id="header" class="navbar">
    <ul class="nav navbar-nav navbar-avatar pull-right">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">            
                <span class="hidden-xs-only">{{usuario_logado}}</span>
                {% if( avatar is empty ) %}
                {% set avatar_user = 'bfdc40e956b123b24b4962cc9409485a.jpg' %} 
                {% else  %}
                {% set avatar_user = empresaId~'/'~id~'/'~'60_'~avatar %} 
                {% endif %}
                <span class="thumb-small avatar inline">{{image( 'img/users/'~avatar_user, 'class':'img-circle') }}</span>
                <b class="caret hidden-xs-only"></b>
            </a>
            <ul class="dropdown-menu">
                <li>{{ link_to("empresa/perfil", 'Perfil') }}</li>
                <li class="divider"></li>
                <li>{{ link_to('session/logout', 'Sair') }}</li>
            </ul>
        </li>
    </ul>
    <a class="navbar-brand" href="#">Incentiv</a>
    <button type="button" class="btn btn-link pull-left nav-toggle visible-xs" data-toggle="class:slide-nav slide-nav-left" data-target="body">
        <i class="fa fa-bars fa-lg text-default"></i>
    </button>
    <ul class="nav navbar-nav hidden-xs">
        <li>
            <div class="m-t m-b-small" id="panel-notifications">
                <a href="#mensagens" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope-o fa-fw fa-lg text-default"></i><b class="badge badge-notes bg-danger count-n">0</b></a>
                <section class="dropdown-menu m-l-small m-t-mini">
                    <section class="panel panel-large arrow arrow-top">
                        <header class="panel-heading bg-white"><span class="h5"><strong>Você tem <span class="count-n">0</span> mensagens não lidas</strong></span></header>
                        <div class="list-group">
                            <a href="#" class="media list-group-item" style="display: none">
                                <span class="media-body block m-b-none">
                                </span>
                            </a>
                        </div>
                        <footer class="panel-footer text-small">
                            <a href="#" class="pull-right"><i class="fa fa-cog"></i></a>
                            {{ link_to('empresa/mensagens', 'Mostrar todas as mensagens') }}
                        </footer>
                    </section>
                </section>
            </div>
        </li>
    </ul>
<!--    {{ form(null, 'class':'navbar-form pull-left shift', 'data-toggle':'shift:appendTo','data-target':'.nav-primary') }}
    <i class="fa fa-search text-muted"></i>
    <input type="text" class="input-sm form-control col-lg-6" placeholder="Colaboradores">
    {{endForm()}}-->
</header>
<!-- / header -->
<!-- nav vertical -->
<nav id="nav" class="nav-primary hidden-xs nav-vertical">
    <ul class="nav" data-spy="affix" data-offset-top="50">
        <li class="dropdown-submenu" id="menu-geral">
            {{ link_to("empresa/geral", '<i class="fa fa-th fa-lg"></i><span>Geral</span>') }}
        </li>
        <li class="dropdown-submenu" id="menu-desafio">
            {{ link_to("empresa/desafio",'data-toggle':'tooltip','data-placement':'right','data-original-title':'Crie desafios aos seus colaboradores',  '<i class="fa fa-exclamation"></i><span>Desafios</span>') }}
        </li>
        <li class="dropdown-submenu" id="menu-noticia">
            {{ link_to("empresa/noticia",'data-toggle':'tooltip','data-placement':'right','data-original-title':'Informe as novidades da empresa pra seus colaboradores', '<i class="fa fa-arrow-circle-right"></i><span>Notícias</span>') }}
        </li>
        <li class="dropdown-submenu" id="menu-colaborador">
            {{ link_to("empresa/colaborador",'data-toggle':'tooltip','data-placement':'right','data-original-title':'Cadastro e alteração dos usuários',  '<i class="fa fa-users fa-lg"></i><span>Usuários</span>') }}
        </li>
        <li class="dropdown-submenu" id="menu-ideia">
            {{ link_to("empresa/ideia",'data-toggle':'tooltip','data-placement':'right','data-original-title':'Ideias enviadas pelos colaboradores', '<i class="fa fa-lightbulb-o fa-lg"></i><span>Banco de ideias</span>') }}
        </li>
        <li class="dropdown-submenu" id="menu-recompensa">
            <a href="#"><i class="fa fa-info fa-lg"></i><span>Incentivs</span></a>
            <ul class="dropdown-menu">
                {% if perfilId == perfilAdmin %}
                    <li>{{ link_to("empresa/recompensa",'data-toggle':'tooltip','data-placement':'right','data-original-title':'Regra de uso dos incentivs (pontos) dos colaboradores', '<span>Criar/Alterar Regras</span>') }}</li>
                    <!--<li>{{ link_to("empresa/recompensa/utilizar-recompensa",'data-toggle':'tooltip','data-placement':'right','data-original-title':'Debitar incentivs do colaborador por uso de recompensa', 'Utilizar') }}</li>-->                    
                {% endif %}
                <li>{{ link_to("empresa/recompensa/ver-pedidos-recompensa",'data-toggle':'tooltip','data-placement':'right','data-original-title':'Pedidos de uso de incentivs (pontos) dos colaboradores', '<span>Ver Pedidos</span>') }}</li>
            </ul>
        </li>
       </li>
        <li class="dropdown-submenu" id="menu-mensagem">
            {{ link_to("empresa/mensagens", 'data-toggle':'tooltip','data-placement':'right','data-original-title':'Todas as mensagens', '<i class="fa fa-envelope-o fa-lg"></i><span>Mensagens</span>') }}
        </li>
<!--        <li class="dropdown-submenu">
            <a href="#"><i class="fa fa-calendar fa-lg"></i><span>Eventos</span></a>
            <ul class="dropdown-menu">
                <li>{{ link_to("empresa/evento/1", 'Palestras') }}</li>
                <li>{{ link_to("empresa/evento/2", 'Outros') }}</li>
            </ul>
        </li>-->
    </ul>
</nav>
<section id="content">
    <section class="main padder">
        {{ content() }}
    </section>
</section>
<!-- footer -->
<footer id="footer">
    <div class="text-center padder clearfix">
        <p>
            <small>&copy; 2015, Redes sociais do Incentiv Go</small><br><br>
            <a href="#" class="btn btn-xs btn-circle btn-twitter"><i class="fa fa-twitter"></i></a>
            <a href="#" class="btn btn-xs btn-circle btn-facebook"><i class="fa fa-facebook"></i></a>
            <a href="#" class="btn btn-xs btn-circle btn-gplus"><i class="fa fa-google-plus"></i></a>
        </p>
    </div>
</footer>