
<form method="post" autocomplete="off">

<ul class="pager">
    <li class="previous pull-left">
        {{ link_to("perfil", "&larr; Voltar") }}
    </li>
    <li class="pull-right">
        {{ submit_button("Salvar", "class": "btn btn-success") }}
    </li>
</ul>

{{ content() }}

<div class="center scaffold">

    <h2>Editar perfil</h2>

    <ul class="nav nav-tabs">
        <li class="active"><a href="#A" data-toggle="tab">Básico</a></li>
        <li><a href="#B" data-toggle="tab">Usuário</a></li>
    </ul>

    <div class="tabbable">
        <div class="tab-content">
            <div class="tab-pane active" id="A">

                {{ form.render("id") }}

                <div class="clearfix">
                    <label for="nome">Nome</label>
                    {{ form.render("nome") }}
                </div>

                <div class="clearfix">
                    <label for="ativo">Ativo?</label>
                    {{ form.render("ativo") }}
                </div>

            </div>

            <div class="tab-pane" id="B">
                <p>
                    <table class="table table-bordered table-striped" align="center">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Nome</th>
                                <th>Banido?</th>
                                <th>Suspenso?</th>
                                <th>Ativo?</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for user in perfil.users %}
                            <tr>
                                <td>{{ user.id }}</td>
                                <td>{{ user.nome }}</td>
                                <td>{{ user.banido == 'Y' ? 'Yes' : 'No' }}</td>
                                <td>{{ user.suspenso == 'Y' ? 'Yes' : 'No' }}</td>
                                <td>{{ user.ativo == 'Y' ? 'Yes' : 'No' }}</td>
                                <td width="12%">{{ link_to("usuario/edit/" ~ user.id, '<i class="icon-pencil"></i> Editar', "class": "btn") }}</td>
                                <td width="12%">{{ link_to("usuario/delete/" ~ user.id, '<i class="icon-remove"></i> Deletar', "class": "btn") }}</td>
                            </tr>
                        {% else %}
                            <tr><td colspan="3" align="center">Não há usuários atribuídos a esse perfil</td></tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </p>
            </div>

        </div>
    </div>

    </form>
</div>