{{hidden_field("dados[id]",'value':id)}}
<section class="main padder">
    <div class="row">
        <div class="col-sm-11">
            <div class="form-group">
                <label class="col-lg-3 control-label">Título</label>
                <div class="col-lg-9 select2-allowclear">
                    {{ text_field("dados[titulo]", 'id':'titulo-noticia','value':titulo,'class':'bg-focus form-control') }}
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-lg-3 control-label">Notícia</label>
                <div class="col-lg-9">
                    {{ text_area("dados[noticia]", 'id':'noticia', 'placeholder': 'Descreva a notícia','value':noticia,'rows':'9', 'class':'bg-focus form-control') }}
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Fim Modal Criar Regra -->
{{ javascript_include('js/empresa/noticia/modal-noticia.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        ModalNoticia.init();
    });
</script>