{{hidden_field("dados[id]",'value':id)}}
<section class="main padder">
    <div class="row">
        <div class="col-sm-11">
            <div class="form-group">
                <label class="col-lg-3 control-label">{{lang['titulo']}}</label>
                <div class="col-lg-9 select2-allowclear">
                    {{ text_field("dados[titulo]", 'id':'titulo-noticia','value':titulo,'class':'bg-focus form-control') }}
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-lg-3 control-label">{{lang['noticia']}}</label>
                <div class="col-lg-9">
                    {{ text_area("dados[noticia]", 'id':'noticia', 'placeholder': lang['descreva_noticia']~'...','value':noticia,'rows':'9', 'class':'bg-focus form-control') }}
                </div>
            </div>
        </div>
    </div>
</section>
{{hidden_field("lang",'value':lang['lang'])}}
<!-- Fim Modal Criar Regra -->
{{ javascript_include('js/empresa/noticia/modal-noticia.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        ModalNoticia.init($("#lang").val());
    });
</script>