<div class="clearfix">
    <h4><i class="fa fa-arrow-circle-right"></i> {{lang['noticias']}}</h4>
</div>
<div class="row">
    <div class="col-lg-12">
        <!-- .breadcrumb -->
        <ul class="breadcrumb">
            <li><a href="#">{{lang['noticias']}}</a></li>
        </ul>
        <!-- / .breadcrumb -->
    </div>
    <div class="col-lg-10 col-lg-offset-1">
        <?php echo $this->flashSession->output(); ?>
        <!-- scrollable inbox widget -->
        <section class="panel">
            <header class="panel-heading">
                <div class="pull-left col-lg-4">
                    <button type="button" class="btn btn-sm btn-facebook squared" id="btnCriarNoticia">{{lang['criar_noticia']}}</button>
                </div>
                <div class="col-lg-4 input-group">
                    <input type="text" id="filterNoticia" class="input-sm form-control" placeholder="{{lang['pesquisar_titulo_descricao']}}...">
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-sm btn-white" id="btnPesquisarNoticia">{{lang['pesquisar']}}</button>
                    </span>
                </div>
            </header>
            <div id="pesquisarNoticia"></div>
        </section>
    </div>
</div>
    <!-- Início Modal Criar Noticia -->
    <div class="modal fade" id="modalCriarNoticia" tabindex="-5" role="dialog" aria-labelledby="modalCriarNoticiaLabel" aria-hidden="true">
        {{ form('empresa/noticia/salvar-noticia', 'class':'form-horizontal', 'id':'form-noticia', 'method': 'post') }}
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">{{lang['fechar']}}</span></button>
                    <h4 class="modal-title" id="myModalLabel"></h4>
                </div>
                <div class="modal-body" id="modal-body-noticia"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-default squared" data-dismiss="modal">{{lang['cancelar']}}</button>
                    <button type="submit" class="btn btn-sm btn-syndicate squared" id="btnSalvarNoticia">{{lang['salvar_noticia']}}</button>
                </div>
            </div>
        </div>
        {{endForm()}}
        {{hidden_field("lang",'value':lang['lang'])}}
    </div>
    <!-- Fim Modal Criar Noticia -->
    {{ javascript_include('js/empresa/noticia/noticia.js') }}
    <script type="text/javascript">
        $(document).ready(function() {
            Noticia.init($("#lang").val());
        });
    </script>