<section id="content">
    <section class="main padder">
        <div class="clearfix">
            <h4><i class="fa fa-edit"></i>Notícias</h4>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <!-- .breadcrumb -->
                <ul class="breadcrumb">
                    <li><a href="#">Notícias</a></li>
                </ul>
                <!-- / .breadcrumb -->
            </div>
            <div class="col-lg-10 col-lg-offset-1" id="mensagem-modal-noticia"><?php echo $this->flashSession->output(); ?></div>
            <div class="col-lg-10 col-lg-offset-1">
                <!-- scrollable inbox widget -->
                <section class="panel">
                    <header class="panel-heading">
                        <div class="pull-left">
                            <button type="button" class="btn btn-sm btn-white squared" id="btnCriarNoticia">Criar Notícia</button>
                        </div>
                        <div class="col-sm-4 col-lg-offset-3">
                            <div class="input-group">
                                <input type="text" id="filterNoticia" class="input-sm form-control" placeholder="Pesquisar por título, descrição">
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-sm btn-white" id="btnPesquisarNoticia">Pesquisar</button>
                                </span>
                            </div>
                        </div>
                        <div class="pull-right">
                            <span class="label label-large bg-default" id="quantidade-noticia" data-placement="left" data-toggle="tooltip" data-original-title="Notícias Cadastradas">0</span> Notícias 
                        </div>
                    </header>
                    <div id="pesquisarNoticia"></div>
                </section>
            </div>
    </section>
</section>
<!-- Início Modal Criar Noticia -->
<div class="modal fade" id="modalCriarNoticia" tabindex="-5" role="dialog" aria-labelledby="modalCriarNoticiaLabel" aria-hidden="true">
   {{ form('empresa/noticia/salvar-noticia', 'class':'form-horizontal', 'id':'form-noticia', 'method': 'post') }}
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                    <h4 class="modal-title" id="myModalLabel"></h4>
                </div>
                <div class="modal-body" id="modal-body-noticia"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-default squared" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-sm btn-syndicate squared" id="btnSalvarNoticia">Salvar notícia</button>
                </div>
            </div>
        </div>
   {{endForm()}}
</div>
<!-- Fim Modal Criar Noticia -->
{{ javascript_include('js/empresa/noticia/noticia.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        Noticia.init();
    });
</script>