
<table class="table table-responsive table-striped table-condensed">
    <tbody>
        {% for noticia in page.items %}
            <tr class="row">
                <td class="td-responsive">
                    <div class="text-muted">
                        <span>
                            {% if(noticia.status == 'N') %}
                                {% set status = 'danger' %} 
                                {% set status_label = lang['inativo'] %}
                            {% else  %}
                                {% set status = 'success' %} 
                                {% set status_label = lang['ativo'] %}
                            {% endif %}
                            <span class="label label-{{status}}" data-placement="right" data-toggle="tooltip" title="Status"> {{status_label}}</span>
                        </span>
                    </div>

                    <div class="btn-group pull-right form-control-static" data-placement="right" data-toggle="tooltip" data-original-title="{{lang['acoes']}}">
                        <button class="dropdown-toggle" role="button" data-toggle="dropdown" ><i class="fa fa-gear"></i></button>
                        <ul class="dropdown-menu pull-right">
                            <li class="text-left"><a href="#" class="btnAlterarNoticia" id="{{noticia.id}}"><i class="icon-pencil"></i> {{lang['alterar']}}</a></li>
                             <li class="divider"></li>
                            {% if(noticia.status == 'N') %}
                                <li class="text-left">{{linkTo('empresa/noticia/ativar-inativar-noticia/Y/'~noticia.id, '<i class="icon-plus-sign"></i>'~lang['ativar'])}}
                            {% else %}
                                <li class="text-left">{{linkTo('empresa/noticia/ativar-inativar-noticia/N/'~noticia.id, '<i class="fa fa-minus-square-o"></i>'~lang['inativar'])}}</li>
                            {% endif %}
                       </ul>
                    </div>
                    <h6>
                        <p>
                            <strong>{{noticia.titulo}}</strong> - 
                            <span data-placement="right" data-toggle="tooltip" data-original-title="{{lang['data_cadastro_noticia']}}" >
                                {% if(lang['lang'] == 'en') %}
                                    {{ date('m/d/Y', noticia.criacaoDt) }}
                                {% else %}
                                    {{ date('d/m/Y', noticia.criacaoDt) }}
                                {% endif %}
                            </span> 
                        </p>{{noticia.noticia}}
                    </h6>
                </td>
            </tr>
        {% elsefor %}
            <tr class="row">
                <td class="table-responsive">
                    <h6 class="text-center text-info">{{lang['nenhuma_noticia']}}</h6>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<section class="panel-footer">
    <footer>
        <div class="row">
            <div class="col-lg-1 text-center"  data-placement="bottom" data-toggle="tooltip" data-original-title="{{lang['noticias_cadastradas']}}: {{page.total_items}}">
                <small class="text-muted inline m-t-small m-b-small"><span class="label label-large bg-default " id="quantidade-desafio">{{page.total_items}}</span> {{lang['noticias']}} </small>
            </div>
            <div class="col-sm-3 col-lg-offset-3 text-center">
                <small class="text-muted inline m-t-small m-b-small">{{lang['p_mostrando']}} {{ page.current }} de {{ page.total_pages }}</small>
            </div>
            <div class="col-sm-5 text-right text-center-sm">                
                <ul class="pagination pagination-small m-t-none m-b-none">
                    <li><a href="#" class="fa btnPaginacaoNoticia" id="1"><i class="icons icon-fast-backward"></i> {{lang['p_primeiro']}}</a></li>
                    <li><a href="#" class="fa btnPaginacaoNoticia" id="{{page.before}}"><i class="icons icon-step-backward"></i> {{lang['p_anterior']}}</a></li>
                    <li><a href="#" class="fa btnPaginacaoNoticia" id="{{page.next}}"><i class="icons icon-step-forward"></i> {{lang['p_proximo']}}</a></li>
                    <li><a href="#" class="fa btnPaginacaoNoticia" id="{{page.last}}">{{lang['p_ultimo']}} <i class="icons icon-fast-forward"></i> </a></li>
                </ul>
                {{hidden_field("quantNoticia","value":page.total_items )}}
            </div>
        </div>
    </footer>
</section>
{{hidden_field("lang",'value':lang['lang'])}}
{{ javascript_include('js/empresa/noticia/pesquisar-noticia.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        pesquisarNoticia.init($("#lang").val());
    });
</script>