{{hidden_field("id",'value':id)}}
<section class="main padder">
    <div class="row">
        <div class="col-sm-11">
            <div class="form-group">
                <label class="col-lg-3 control-label">Perfil</label>
                <div class="col-lg-9">
                    {{ select("perfilId", perfis, 'using': ['id', 'nome'], 'value': perfilId, 'class':'bg-focus form-control') }}
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Nome</label>
                <div class="col-lg-9">
                    {{ text_field("nome", 'id':'nome', 'placeholder': 'Informe o nome','value':nome, 'class':'bg-focus form-control') }}
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Email</label>
                <div class="col-lg-9">
                    {{ email_field(["email", 'id':'email', 'placeholder': 'Informe o e-mail','value':email, 'class':'bg-focus form-control']) }}
                </div>
            </div>
            
        </div>
    </div>
</section>
{{ javascript_include('js/empresa/colaborador/modal-colaborador.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        ModalColaborador.init();
    });
</script>