
<table class="table table-responsive table-striped table-condensed">
    <tbody>
        {% for colaborador in page.items %}
            <tr class="row">
                <td class="td-responsive">
                    <div class="text-muted">
                        <span>
                            {% if(colaborador.status == 'N') %}
                                {% set status = 'danger' %} 
                                {% set status_label = 'Inativo' %}
                            {% else  %}
                                {% set status = 'success' %} 
                                {% set status_label = 'Ativo' %}
                            {% endif %}
                            <span class="label label-{{status}}" data-placement="left" data-toggle="tooltip" title="Status"> {{status_label}}</span>
                        </span>
                        <span class="label label-info" data-placement="right" data-toggle="tooltip" title="Pontos Acumulados">3 pontos</span>
                    </div>
                    <div class="btn-group pull-right" data-placement="top" data-toggle="tooltip" data-original-title="Ações">
                        <button class="dropdown-toggle" role="button" data-toggle="dropdown" ><i class="fa fa-gear"></i></button>
                        <ul class="dropdown-menu pull-right">
                            <li class="text-left"><a href="#" class="btnAlterarColaborador" id="{{colaborador.id}}"><i class="icon-pencil"></i> Alterar</a></li>
                            <li class="divider"></li>
                            {% if(colaborador.status == 'N') %}
                            <li class="text-left">{{linkTo('empresa/colaborador/ativar-inativar-colaborador/Y/'~colaborador.id, '<i class="icon-plus-sign"></i> Ativar')}}
                                {% else %}
                            <li class="text-left">{{linkTo('empresa/colaborador/ativar-inativar-colaborador/N/'~colaborador.id, '<i class="fa fa-minus-square-o"></i> Inativar')}}</li>
                                {% endif %}
                            <!--<li class="text-left"><a href="#" id="{{colaborador.id}}"><i class="icon-remove"></i> Deletar</a> </li>-->
                        </ul>
                    </div>
                    <h5>{{colaborador.nome}}<br/><h6>{{colaborador.email}}</h6></h5>  
                </td>
            </tr>
        {% elsefor %}
            <tr class="row">
                <td class="table-responsive">
                    <h6 class="text-center text-info">Nenhum colaborador cadastrado.</h6>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<section class="panel-footer">
    <footer>
        <div class="row">
            <div class="col-sm-4 col-sm-offset-3 text-center">
                <small class="text-muted inline m-t-small m-b-small">Mostrando {{ page.current }} de {{ page.total_pages }}</small>
            </div>
            <div class="col-sm-5 text-right text-center-sm">                
                <ul class="pagination pagination-small m-t-none m-b-none">
                    <li><a href="#" class="fa btnPaginacaoColaborador" id="1"><i class="icons icon-fast-backward"></i> Primeiro</a></li>
                    <li><a href="#" class="fa btnPaginacaoColaborador" id="{{page.before}}"><i class="icons icon-step-backward"></i> Anterior</a></li>
                    <li><a href="#" class="fa btnPaginacaoColaborador" id="{{page.next}}"><i class="icons icon-step-forward"></i> Próximo</a></li>
                    <li><a href="#" class="fa btnPaginacaoColaborador" id="{{page.last}}">Último <i class="icons icon-fast-forward"></i> </a></li>
                </ul>
                {{hidden_field("quantColaborador","value":page.total_items )}}
            </div>
        </div>
    </footer>
</section>
{{ javascript_include('js/empresa/colaborador/pesquisar-colaborador.js') }}
<script type="text/javascript">  
    $(document).ready(function(){
        pesquisarColaborador.init();
    });       
</script>