<tbody>
    <tr>
        <td style="padding:40px 0  0 0;">
            <p style="color:#000;font-size: 16px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;font-weight:normal;">

            <h2 style="font-size: 14px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">Novo Desafio</h2>

            <p style="font-size: 13px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">
                Que legal {{ nome }}. Você recebeu um novo desafio, estão contanto com seu talento.<br/> Entre no Incentiv Go
                e confira o que há de novo para você agora, boa sorte e um ótimo desafio.

                <br>
                <br>
                <a style="background:#E86537;color:#fff;padding:10px" href="http://{{ publicUrl }}{{ loginUrl }}">Entrar</a>

                <br>
                <br>
                Incentiv Go
                <br>
            </p>
        </td>
    </tr>
</tbody>