<tbody>
    <tr>
        <td style="padding:40px 0  0 0;">
            <p style="color:#000;font-size: 16px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;font-weight:normal;">

            <h2 style="font-size: 14px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">{{redefinir_sua_senha}}</h2>

            <p style="font-size: 13px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">{{txt_redefinir_senha}}

                <br>
                <br>
                <a style="background:#E86537;color:#fff;padding:10px" href="http://{{ publicUrl }}{{ resetUrl }}">{{redefinir}}</a>

                <br>
                <br>
                Incentiv Go
                <br>
            </p>
        </td>
    </tr>
</tbody>