
<form method="post" autocomplete="off">

<ul class="pager">
    <li class="previous pull-left">
        {{ link_to("usuario", "&larr; Voltar") }}
    </li>
    <li class="pull-right">
        {{ submit_button("Salvar", "class": "btn btn-success") }}
    </li>
</ul>

{{ content() }}

<div class="center scaffold">
    <h2>Criar um usuário</h2>

    <div class="clearfix">
        <label for="nome">Nome</label>
        {{ form.render("nome") }}
    </div>

    <div class="clearfix">
        <label for="email">E-Mail</label>
        {{ form.render("email") }}
    </div>

    <div class="clearfix">
        <label for="perfilId">Perfil</label>
        {{ form.render("perfilId") }}
    </div>

</div>

</form>