<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"> 
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="description" content="Programa de incentivo a colaboradores de empresas" />
        <meta name="author" content="André Maciel Fagundes">
        <meta name="keywords" content="incentivo, empresas, business, corporações, corporation"/>
        <meta name="robots" content="index,follow,noodp,noydir" />
        <title>Bem-vindo ao Incentiv</title>

        <link rel="canonical" href="http://www.incentiv.com.br/" />
        <link rel="shortcut icon" href="" />
        
        {{ javascript_include('js/modernizr.js') }}
        <!-- Le styles -->
        {{ stylesheet_link('css/bootstrap/bootstrap.min.css') }}
        {{ stylesheet_link('css/fonts/font-awesome.min.css') }}
        {{ stylesheet_link('css/fonts/font.css') }}
        {{ stylesheet_link('css/fonts/lineicons/style.css') }}
        {{ stylesheet_link('http://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css', false) }}
        {{ stylesheet_link('css/colaborador/style-colaborador.css') }}
        
        {{ javascript_include('js/jquery.min.js') }}
        {{ javascript_include('js/bootstrap.min.js') }}
        {{ javascript_include('js/jquery.validate.min.js') }}
        {{ javascript_include('js/colaborador/js-library/chart-master/Chart.js') }}

    </head>

    <body  data-spy="scroll" data-target=".navbar" data-offset='61' >

    {{ content() }} 
         
    {{ javascript_include('js/colaborador/jquery.dcjqaccordion.2.7.js') }}
    {{ javascript_include('js/colaborador/jquery.nicescroll.js') }}
    {{ javascript_include('js/colaborador/jquery.scrollTo.min.js') }}
    {{ javascript_include('js/colaborador/jquery.sparkline.js') }}
    {{ javascript_include('js/colaborador/common-scripts.js') }}
    {{ javascript_include('js/colaborador/moment.min.js') }}
    {{ javascript_include('js/colaborador/moment.locale.min.js') }}
    </body>
</html>