<div class="clearfix">
    <h4><i class="fa fa-edit"></i>Personalizar</h4>
</div>
<div class="row">
    <div class="col-sm-8 col-sm-push-2">
        <section class="panel">
            <div class="panel-body">
                {{ form('empresa/personalizar', 'class':'form-horizontal', 'id':'form-personalizar', 'method': 'post', 'enctype':'multipart/form-data') }}
                {{hidden_field('empresaId','name':'dados[id]','value':empresa.id)}}
                {{hidden_field('logo_hidden','value':empresa.logo)}}
                <div class="row pager">
                    <div class="col-xs-12 col-md-4">
                        <input class="col-md-4" id="input-logo" name="logo" type="file" accept="image/*" >
                        <div id="errorBlock43" class="help-block"></div>
                    </div>
                    <div class="col-xs-12 col-md-8">
                        <div id="mensagem-modal-resposta-personalizar" class="center"><?php echo $this->flashSession->output(); ?></div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Url:</label>
                            <div class="col-sm-8">
                                <div class="input-group">
                                    {{ text_field("dados[subdominio]", 'id':'subdominio','value':empresa.subdominio,'class': 'form-control text-right','disabled':'disabled', 'placeholder':'subdominio') }}
                                    <span class="input-group-addon" id="basic-addon2">.incentivgo.com.br</span>
                                </div>
                                <label id="perfil-nome-error" class="error text-left" for="subdominio" style="display: none;">Campo obrigatório</label>
                            </div>

                        </div>
                        <div class="form-group">
                            <label for="nome" class="col-sm-2 control-label">Empresa:</label>
                            <div class="col-sm-8">
                                {{ text_field("dados[nome]", 'id':'nome','value':empresa.nome,'class': 'form-control', 'placeholder':'Nome') }}
                                <label id="personalizar-nome-error" class="error pull-left display-none" for="nome" style="display: none;">Campo obrigatório</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-10">
                                {{ submit_button('Salvar Personalização','class':'btn btn-theme04 btn-facebook btn-sm squared') }}
                            </div>
                        </div>
                    </div>
                </div>
                {{endForm()}}
            </div>
        </section>
    </div>
</div>
{{ javascript_include('js/empresa/personalizar/perfil.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        PerfilEmpresa.init();
    });
</script>