<section class="components">
    <div class="container margin">
        <div class="row col-sm-offset-4">
            <h6><strong> {{lang['alterar_senha']}}.</strong></h6>
            {{ form('class': 'form-horizontal form-login','role': 'form', 'autocomplete': 'off') }}
                <div class="form-group">
                    <div class="col-sm-5 col-lg-5">
                        <?php echo $this->flashSession->output(); ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-5 col-lg-5">
                        {{ form.render('senha') }}
                        {{ form.messages('senha') }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-5 col-lg-5">
                         {{ form.render("confirmSenha") }}
                         {{ form.messages('confirmSenha') }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-5 col-lg-5">
                        {{ form.render('go') }}
                    </div>
                </div>
                {{ form.render('csrf') }}
             {{ endform()}}
        </div>
    </div>
</section>