<div class="row m-t-large">
    <div class="col-lg-6">
        <div class="row">
            <!-- easypiechart -->
            <div class="col-xs-6">              
                <section class="panel">
                    <header class="panel-heading bg-white">
                        <div class="text-center h5">Desafios Criados</div>
                    </header>
                    <div class="panel-body pull-in text-center">
                        <div class="inline">
                            <div class="easypiechart">
                                <span class="h1" style="display:inline-block">{{count_desafios}}</span>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <div class="col-xs-6">
                <section class="panel">
                    <header class="panel-heading bg-white">
                        <div class="text-center h5">Usuários</div>
                    </header>
                    <div class="panel-body pull-in text-center">
                        <div class="inline">
                            <div class="easypiechart center">
                                <span class="h1" style="display:inline-block">{{count_usuarios}}</span>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <!-- easypiechart end-->
        </div>
        <section class="panel">
            <div class="panel-body text-muted l-h-2x text-center">
                <span class="badge bg-info">{{count_pontuacao_total_gerada}}</span>
                <span class="m-r-small">Pontuação total gerada</span>
                <span class="badge bg-danger">{{count_pedidos_incentiv}}</span>
                <span class="m-r-small">{{ link_to("empresa/recompensa/ver-pedidos-recompensa",'data-toggle':'tooltip','data-placement':'bottom','data-original-title':'Pedidos de uso de incentivs (pontos) dos colaboradores para baixa', 'Pedidos de uso de incentivs') }}</span>
                <span class="badge bg-danger">{{count_ideias_aprovacao}}</span>
                <span class="m-r-small">{{ link_to("empresa/ideia",'data-toggle':'tooltip','data-placement':'bottom','data-original-title':'Ideias enviadas pelos colaboradores para aprovação', 'Ideias para aprovação') }}</span>
            </div>
        </section>
    </div>
    <div class="col-lg-6">
        <section class="panel">
            <header class="panel-heading">
                <span class="label label-large bg-default">{{count_desafios_cumpridos}}</span> Desafios Cumpridos para Aprovação
            </header>
            <?php echo $this->flashSession->output(); ?>
            <table class="table table-responsive table-striped table-condensed">
                <tbody>
                    {% for desafio in desafios_cumpridos %}
                        <tr class="row">
                            <td class="td-responsive">
                                {% if(desafio['tipo'] is 1) %}
                                {% set tipo = 'info' %} 
                                {% set tipo_label = 'Individual' %}
                                {% elseif(desafio['tipo'] is 2)  %}
                                {% set tipo = 'success' %} 
                                {% set tipo_label = 'Por Equipe' %}
                                {% endif %}
                                <span class="label label-{{tipo}}" data-placement="left" data-toggle="tooltip" title="Tipo de Desafio"> {{tipo_label}}</span>
                                <div class="btn-group" data-placement="right" data-toggle="tooltip" data-original-title="Ações">
                                    <button class="dropdown-toggle" role="button" data-toggle="dropdown" ><i class="fa fa-gear"></i></button>
                                    <ul class="dropdown-menu pull-left">
                                        <li class="text-left"><a href="#" class="btnAnalisar" id="{{desafio['id']}}"><i class="icon-angle-down"></i> Analisar</a></li>
                                    </ul>
                                </div>
                                <h6>{{desafio['desafio']}}</h6>
                            </td>
                        </tr>
                    {% elsefor %}
                        <tr class="row">
                            <td class="table-responsive">
                                <h6 class="text-center text-info">Nenhum desafio para aprovação neste momento.</h6>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </section>
    </div>
</div>
<!-- Início Modal Criar Desafio -->
<div class="modal fade" id="modalAnalisarDesafio" tabindex="-5" role="dialog" aria-labelledby="modalAnalisarDesafioLabel" aria-hidden="true">
    {{ form('empresa/desafio/analisar-desafio', 'class':'form-horizontal', 'id':'form-analisar-desafio', 'method': 'post') }}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title" id="myModalLabelDesafios"></h4>
            </div>
            <div class="modal-body" id="modal-body-analisar-desafio"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-default squared" data-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-sm btn-syndicate squared" id="btnReprovarDesafio">Reprovar</button>
                <button type="submit" class="btn btn-sm btn-syndicate squared" id="btnAprovarDesafio">Aprovar</button>
            </div>
        </div>
    </div>
    {{endForm()}}
</div>
<!-- Fim Modal Criar Desafio -->
{{ javascript_include('js/empresa/desafio/index.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        Index.init();
    });
</script>