<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
        <meta name="description" content="Plataforma Web Corporativa de incentivo, motivação a colaboradores de empresas" >
        <meta name="author" content="André Maciel Fagundes">
        <meta name="keywords" content="incentivo, motivação, desafios, empresas, business, corporações, corporation">
        <meta name="robots" content="index,follow,noodp,noydir" >
        <title>Bem-vindo ao Incentiv Go</title>

        <link rel="canonical" href="http://beta.incentivgo.com.br/" >
        <link rel="shortcut icon" href="" >

        {{ javascript_include('js/modernizr.js') }}
        <!-- Le styles -->
        {{ stylesheet_link('css/bootstrap/bootstrap.min.css') }}
        {{ stylesheet_link('css/style.css') }}
        {{ stylesheet_link('http://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css', false) }}
        {{ stylesheet_link('http://fonts.googleapis.com/css?family=Raleway:200,400', false) }}
        {{ stylesheet_link('css/select2.css') }}
        <!--[if lt IE 9]>
            <script src="js/html5shiv.js"></script>
        <![endif]-->
    </head>

    <body data-spy="scroll" data-target=".navbar" data-offset='61'>
        {{ javascript_include('js/jquery.min.js') }}
        {{ javascript_include('js/bootstrap.min.js') }}
        {{ content() }}
        

        <!--[if lte IE 8]>
                {{ javascript_include('js/respond.min.js') }}
	<![endif]-->
        {{ javascript_include('js/retina.min.js') }}
        {{ javascript_include('js/jquery.easing.js') }}
        {{ javascript_include('js/jquery.fitvids.min.js') }}
        {{ javascript_include('js/jquery.nicescroll.min.js') }}
        {{ javascript_include('js/skrollr.js') }}
        {{ javascript_include('js/jquery.touchwipe.min.js') }}
        {{ javascript_include('js/jquery.mask.min.js') }}
        
        <!--select2--> 
        {{ javascript_include('js/select2.min.js') }}
        {{ javascript_include('js/select2_locale_pt-BR.js') }}
        
        <!--[if lt IE 9]>
            {{ javascript_include('js/skrollr.ie.min.js') }}
        <![endif]-->
        {{ javascript_include('js/guideline.main.js') }}
        {{ javascript_include('js/toucheffects.js') }}
        <!--{{ javascript_include('js/modals.js') }}-->
        <!--{{ javascript_include('js/jquery.form.js') }}-->
        <script type="text/javascript">
            if ($('.navbar-toggle:visible').length) {
                    $('.navbar a').click(function () { $(".nav-collapse").collapse("hide"); });
            }
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
            ga('create', 'UA-65622189-1', 'auto');
            ga('send', 'pageview');
        </script>
        {{ javascript_include('js/custom.js') }}
    </body>
</html>