<tbody>
    <tr>
        <td style="padding:40px 0  0 0;">
            <p style="color:#000;font-size: 16px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;font-weight:normal;">

            <h2 style="font-size: 14px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">Redefinir sua senha</h2>

            <p style="font-size: 13px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">Para redefinir a senha na conta Incentiv associada a seu e-mail, clique no botão abaixo. Se você não deseja redefinir sua senha, por favor desconsidere este e-mail.

                <br>
                <br>
                <a style="background:#E86537;color:#fff;padding:10px" href="http://{{ publicUrl }}{{ resetUrl }}">Redefinir</a>

                <br>
                <br>
                IncentivGo
                <br>
            </p>
        </td>
    </tr>
</tbody>