<!--start navigation-->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container" data-start="padding: 15px 0px;" data-200="padding: 0px 0px;">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#intro" class="navbar-brand margin"><span class="incentiv">Incentiv </span><span class="go">Go</span> <span class="h6">beta</span></a>
            <div class="collapse navbar-collapse navbar-responsive-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#intro">Início</a></li>
                    <li><a href="#services">Como funciona?</a></li>
                    <li>{{ link_to("contato", "Contato") }}</li>
                </ul>
                <div class="navbar-right navbar-responsive-collapse">
                    <div class="navbar-btn">
                        {{ link_to("corporation", 'class':'btn btn-syndicate squared', "Entrar") }}
                        {{ link_to("session/cadastro", 'class':'btn btn-sun squared', "Cadastrar Empresa") }}
                    </div>
                </div>
            </div>
        </div>
    </nav>
<!--end navigation-->
{{ content() }}