<!--start navigation-->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    {{ link_to("", 'class':'navbar-brand', '<img title="Incentiv Go" class="logo" src="/img/logotipo-incentiv-go-curvas-01-logo-new.png">') }}
                </div>
                <div class="navbar-collapse collapse navbar-responsive-collapse" id="navbar">
                    <ul class="nav navbar-nav">
                        <li><a href="#intro">{{lang['inicio']}}</a></li>
                        <li><a href="#services">{{lang['como_funciona']}}</a></li>
                        <li>{{ link_to("contato", lang['contato']) }}</li>
                    </ul>
                    <div class="navbar-right center-block">
                        <div class="navbar-btn">
                            {{ link_to("corporation", 'class':'btn btn-syndicate squared', lang['entrar']) }}
                            {{ link_to("session/cadastro", 'class':'btn btn-sun squared', lang['cadastrar_empresa']) }}
                        </div>
                    </div>
                </div>
        </div>
    </nav>
<!--end navigation-->
{{ content() }}