<!--start navigation-->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-responsive-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                {{ link_to("", 'class':'navbar-brand', '<img title="Incentiv Go" class="logo" src="/img/logotipo-incentiv-go-curvas-01-logo-new.png">') }}
            </div>
            <div class="collapse navbar-collapse navbar-responsive-collapse" id="navbar-responsive-collapse">
                <div class="navbar-right">
                    <div class="navbar-btn">
                        {{ link_to("", 'class':'btn btn-link squared', lang['voltar']) }}
                    </div>
                </div>
            </div>
        </div>
    </nav>
<!--end navigation-->
{{ content() }}