
{{ content() }}

<form method="post">

    <h2>Gerenciar Permissões</h2>

    <div class="well" align="center">

        <table class="perms">
            <tr>
                <td><label for="perfilId">Perfil</label></td>
                <td>{{ select('perfilId', perfis, 'using': ['id', 'nome'], 'useEmpty': true, 'emptyText': '...', 'emptyValue': '') }}</td>
                <td>{{ submit_button('Procurar', 'class': 'btn btn-primary') }}</td>
            </tr>
        </table>

    </div>

    {% if request.isPost() and perfil %}

    {% for resource, actions in acl.getResources() %}

    <h3>{{ resource }}</h3>

    <table class="table table-bordered table-striped" align="center">
        <thead>
            <tr>
                <th width="5%"></th>
                <th>Descrição</th>
            </tr>
        </thead>
        <tbody>
            {% for action in actions %}
            <tr>
                <td align="center"><input type="checkbox" name="permissions[]" value="{{ resource ~ '.' ~ action }}"  {% if permissions[resource ~ '.' ~ action] is defined %} checked="checked" {% endif %}></td>
                <td>{{ acl.getActionDescription(action) ~ ' ' ~ resource }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% endfor %}

    {% endif %}

</form>