<div class="clearfix">
    <h4><i class="fa fa-edit"></i>{{lang['perfil']}}</h4>
</div>
<div class="row">
    <div class="col-sm-8 col-sm-push-2">
        <section class="panel">
            <div class="panel-body">
                {{ form('empresa/perfil', 'class':'form-horizontal', 'id':'form-perfil', 'method': 'post', 'enctype':'multipart/form-data') }}
                {{hidden_field('usuarioId','name':'dados[id]','value':usuario.id)}}
                {{hidden_field('empresaId','value':usuario.empresaId)}}
                {{hidden_field('avatar','value':usuario.avatar)}}
                <div class="row pager">
                    <div class="col-xs-12 col-md-4">
                        <input class="col-md-4" id="input-avatar" style="width: 100%;height: 100%; position:absolute; right: 0px;" name="avatar" type="file" accept="image/*" >
                        <div id="errorBlock43" class="help-block"></div>
                    </div>
                    <div class="col-xs-12 col-md-8">
                        <div id="mensagem-modal-resposta-perfil" class="center"><?php echo $this->flashSession->output(); ?></div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-3 control-label">{{lang['nome']}}:</label>
                            <div class="col-sm-9">
                                {{ text_field("dados[nome]", 'id':'nome','value':usuario.nome,'class': 'form-control required', 'placeholder':lang['nome']) }}
                                <label id="nome-error" class="error  pull-left" for="nome" style="display: none;">{{lang['campo_obrigatorio']}}</label>
                            </div>
                            
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-3 control-label">{{lang['email']}}:</label>
                            <div class="col-sm-9">
                                {{ email_field(["dados[email]", 'id':'email','value':usuario.email,'class': 'form-control required', 'placeholder':lang['email']]) }}
                                <label id="email-error" class="error pull-left" for="email" style="display: none;">{{lang['campo_obrigatorio']}}</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-3 control-label">{{lang['cargo']}}:</label>
                            <div class="col-sm-6">
                                {{ text_field("dados[cargo]", 'id':'cargo','value':usuario.cargo,'class': 'form-control', 'placeholder':lang['cargo']) }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-3 control-label">{{lang['data_de_nascimento']}}:</label>
                            <div class="col-sm-4">
                                <div class="input-group date" id="dt-nascimento">
                                    {{ text_field('dados[dt_nascimento]', 'id':'dt_nascimento','value':usuario.nascimentoDt, 'class':'form-control', 'placeholder':'99/99/9999') }}
                                    <span class="input-group-addon">
                                        <span class="fa fa-calendar"></span>
                                    </span>
                                </div>
                                <label id="data_inicio-error" class="error" for="dt_nascimento" style="display: none">{{lang['campo_obrigatorio']}}</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-10">
                                {{ submit_button(lang['Save profile'],'class':'btn btn-theme04 btn-facebook btn-sm squared') }}
                            </div>
                        </div>
                    </div>
                </div>
                {{endForm()}}
            </div>
        </section>
    </div>
    {{hidden_field("lang",'value':lang['lang'])}}
</div>
{{ javascript_include('js/empresa/perfil/perfil.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        Perfil.init($("#lang").val());
    });
</script>