<div class="col-lg-3 ds pull-right">
    {{hidden_field("idUsuario",'value':usuario_id)}}
    <h3>Colaboradores</h3>
    {% for usuario in usuarios %}
        {% if(usuario['id'] != usuario_id) %}
        <div class="desc chat-contacts offline"  data-user-id="{{usuario['id']}}" id="user_{{usuario['id']}}">
            <div class="thumb">
                {{image( 'img/'~usuario['avatar'],'class':'img-circle','width':'35px','height':'35px','align':'') }}
            </div>
            <div class="details">
                <p>
                    <a href="#" class="contact-name">{{usuario['nome']}}</a><br/>
                <muted>{{usuario['email']}}</muted>
                <span class="status"></span>
                </p>
            </div>
        </div>
        {% endif %}
    {% endfor %}
</div>
<script type="text/javascript" src="http://localhost:8088/socket.io/socket.io.js"></script>
{{ javascript_include('js/chat/chat.js') }}
<script type="text/javascript">
    $(document).ready(function(){
        Chat.init(); 
    });
</script>