<div class="col-lg-3 ds pull-right">
    {{hidden_field("idUsuario",'value':usuario_id)}}
    <h3>{{lang['colaboradores']}}</h3>
    {% for usuario in usuarios %}
        {% if(usuario['id'] != usuario_id) %}
            <div class="desc chat-contacts offline"  data-user-id="{{usuario['id']}}" id="user_{{usuario['id']}}">
                <div class="thumb"> 
                    {% if( usuario['avatar'] is empty ) %}
                        {% set avatar = 'bfdc40e956b123b24b4962cc9409485a.jpg' %} 
                    {% else  %}
                        {% set avatar = usuario['empresaId']~'/'~usuario['id']~'/40_'~usuario['avatar'] %} 
                    {% endif %}
                    {{image( 'img/users/'~avatar,'class':'img-circle','width':'40px','height':'40px','align':'') }}
                </div>
                <div class="details">
                    <p>
                        <a href="#" class="contact-name">{{usuario['nome']}}</a><br/>
                    <muted>{{usuario['email']}}</muted>
                    <muted>{{usuario['cargo']}}</muted>
                    <span class="status" data-container="body" data-placement="left" data-title="offline" data-trigger="hover" data-toggle="tooltip"></span>
                    </p>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>
{{ javascript_include('js/chat/chat.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        Chat.init();
    });
</script>