<!-- / nav -->
<section id="content">
    <section class="main padder">
        <div class="clearfix">
            <h4><i class="fa fa-edit"></i>Campanhas</h4>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <!-- .breadcrumb -->
                <ul class="breadcrumb">
                    <li><a href="#">Campanhas</a></li>
                </ul>
                <!-- / .breadcrumb -->
            </div>
            <div class="col-lg-10 col-lg-offset-1">
                <section class="panel">
                    <header class="panel-heading">
                        {{link_to('empresa/criar-campanha','class':'btn btn-sm btn-white squared','Criar Campanha')}}
                    </header>
                    <div id="pesquisarCampanhas"></div>
                </section>
            </div>
        </div>
    </section>
</section>
{{ javascript_include('js/empresa/campanhas/campanhas.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        Campanhas.init();
    });
</script>