<!-- / nav -->
<section id="content">
    <section class="main padder">
        <div class="clearfix">
            <h4><i class="fa fa-users"></i>Colaboradores</h4>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <!-- .breadcrumb -->
                <ul class="breadcrumb">
                    <li><a href="#">Colaboradores</a></li>
                </ul>
                <!-- / .breadcrumb -->
            </div>
            <div class="col-lg-10 col-lg-offset-1">
                <section class="panel">
                    <div class="panel-body">
                        <div class="row text-small">
                            <div class="col-sm-4 m-b-mini">
                                <div class="btn-group" data-toggle="buttons">
                                    <label class="btn btn-sm btn-white">
                                        <input type="checkbox" name="status" value="S"> Ativos
                                    </label>
                                    <label class="btn btn-sm btn-white">
                                        <input type="checkbox" name="status" value="N"> Inativos
                                    </label>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="input-group">
                                    <input type="text" id="filter" class="input-sm form-control" placeholder="Pesquisar por Colaborador">
                                    <span class="input-group-btn">
                                        <button type="button" class="btn btn-sm btn-white" id="btnPesquisarColaboradores">Pesquisar</button>
                                    </span>
                                </div>
                            </div>                            
                        </div>
                    </div>
                    <div id="pesquisarColaborador" class="table-responsive"></div>
                </section>
            </div>
        </div>
    </section>
</section>
{{ javascript_include('js/empresa/colaboradores/colaboradores.js') }}
<script type="text/javascript">  
    $(document).ready(function(){
        Colaboradores.init();
    });   
</script>