<section id="content">
    <section class="main padder">
        <div class="clearfix">
            <h4><i class="fa fa-magic"></i>Criar Campanha</h4>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <!-- .breadcrumb -->
                <ul class="breadcrumb">
                    <li>{{link_to('empresa/campanhas','Campanhas')}}</li>
                    <li class="active">Criar Campanha</li>
                </ul>
                <!-- / .breadcrumb -->
            </div>
            <div class="col-lg-8 col-lg-offset-2">
                <section class="panel clearfix"> 
                    <section class="panel-footer text-center">Informe os dados da Campanha (Semestral ou Anual)</section>
                    {{ form('empresa/criar-campanha', 'class':'form-horizontal', 'id':'criar-campanha', 'method': 'post') }}

                        <div class="step-content">
                            <div class="step-pane active show col-lg-offset-1">
                                <section class="main padder">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <div class="form-group">
                                                <label for="nome" class="col-lg-3 control-label">Nome da Campanha</label>
                                                <div class="col-lg-7">
                                                    {{ text_field("dados[nome]", 'id': 'nome', 'class':'bg-focus form-control','value':nome) }}
                                                    <div class="line line-dashed m-t-large"></div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="data_inicio" class="col-lg-3 control-label">Data de início</label>
                                                <div class="col-lg-2-4">
                                                    {{ date_field("dados[data_inicio]", 'id':'data_inicio', 'data-date-format': 'dd/mm/yyyy', 'class':'bg-focus form-control datepicker') }}
                                                    <div class="line line-dashed m-t-large"></div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="data_fim" class="col-lg-3 control-label">Data de início</label>
                                          
                                                <div class="col-lg-2-4">
                                                    {{ date_field('dados[data_fim]', 'id':'data_fim', 'data-date-format': 'dd/mm/yyyy', 'class':'bg-focus form-control datepicker') }}
                                                    <div class="line line-dashed m-t-large"></div>
                                                </div>

                                            </div>
                                            <div class="form-group">
                                                <label for="ds_observacao" class="col-lg-3 control-label">Observações</label>
                                                <div class="col-lg-7">
                                                    {{ text_area("dados[ds_observacao]", 'id':'ds_observacao', 'placeholder': 'Observações','rows':'5', 'class':'form-control') }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </section>
                                <div class="actions m-t text-center">
                                    <button type="button" class="btn btn-sm btn-white squared">Cancelar</button>
                                    {{submit_button("Salvar",'class':'btn btn-sm btn-syndicate squared')}}
                                </div>
                            </div>
                        </div>
                   {{endForm()}}
                </section>
            </div>
        </div>
    </section>
</section>
<!-- Início Modal Criar Regra -->
<div class="modal fade" id="modalCriarRegras" tabindex="-5" role="dialog" aria-labelledby="modalCriarRegrasLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title" id="myModalLabel">Incluir Regra</h4>
            </div>
            <div class="modal-body">
                <section class="main padder">
                    <div class="row">
                        <div class="col-sm-11 col-lg-offset-1">
                            <div class="form-group">
                                <label class="col-lg-3 control-label">Regra</label>
                                <div class="col-lg-9">
                                    <input class="bg-focus form-control" type="text" name="[dados][regra][regra]" id="nome" >
                                    <div class="line line-dashed m-t-large"></div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-3 control-label">Pontuação</label>
                                <div class="col-lg-9">
                                    <div class="spinner input-group m-b col-lg-3" id="MySpinner">
                                        <input type="text" maxlength="3" name="spinner" class="input-sm spinner-input form-control">
                                        <div class="btn-group btn-group-vertical input-group-btn">
                                            <button class="btn btn-white spinner-up" type="button">
                                                <i class="fa fa-chevron-up"></i>
                                            </button>
                                            <button class="btn btn-white spinner-down" type="button">
                                                <i class="fa fa-chevron-down"></i>
                                            </button>
                                        </div>
                                    </div>
                                    <div class="line line-dashed m-t-large"></div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-3 control-label">Observações</label>
                                <div class="col-lg-9">
                                    <textarea placeholder="Observações" rows="5" class="form-control"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-default squared" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-sm btn-syndicate squared">Incluir regra</button>
            </div>
        </div>
    </div>
</div>
<!-- Fim Modal Criar Regra -->
{{ javascript_include('js/empresa/campanhas/criar-campanha.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        CriarCampanha.init();
    });
</script>