<div class="row m-t-large">
    <div class="col-lg-6">
        <div class="row">
            <!-- easypiechart -->
            <div class="col-xs-6">              
                <section class="panel">
                    <header class="panel-heading bg-white">
                        <div class="text-center h5">Desafios</div>
                    </header>
                    <div class="panel-body pull-in text-center">
                        <div class="inline">
                            <div class="easypiechart">
                                <span class="h2" style="margin-left:10px;margin-top:10px;display:inline-block">540</span>
                                <div class="easypie-text text-muted">ativos</div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <div class="col-xs-6">
                <section class="panel">
                    <header class="panel-heading bg-white">
                        <div class="text-center h5">Usuários</div>
                    </header>
                    <div class="panel-body pull-in text-center">
                        <div class="inline">
                            <div class="easypiechart center">
                                <span class="h2" style="margin-left:10px;margin-top:10px;display:inline-block">75</span>
                                <div class="easypie-text text-muted">ativos</div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <!-- easypiechart end-->
        </div>
        <section class="panel">
            <div class="panel-body text-muted l-h-2x text-center">
                <span class="badge">5.489</span>
                <span class="m-r-small">Pontuação total gerada</span>
                <span class="badge bg-danger">5</span>
                <span class="m-r-small">Novas mensagens</span>
            </div>
        </section>
    </div>
    <div class="col-lg-6">
        <!-- scrollable inbox widget -->
        <section class="panel">
            <header class="panel-heading">
                <ul class="nav nav-pills pull-right">
                    <li>
                        <a href="#" class="panel-toggle text-muted"><i class="fa fa-caret-down fa-lg text-active"></i><i class="fa fa-caret-up fa-lg text"></i></a>
                    </li>
                </ul>
                <span class="label label-large bg-default">15</span> Desafios Cumpridos
            </header>
            <section style="height:234px" class="panel-body scrollbar scroll-y m-b">
                <article class="media">
                    <span class="pull-left thumb-small"><img src="img/avatar.jpg" alt="John said" class="img-circle"></span>
                    <div class="media-body">
                        <div class="pull-right media-mini text-center text-muted">
                            <strong class="h4">12:18</strong><br>
                            <small class="label bg-light">pm</small>
                        </div>
                        <a href="#" class="h4">Livraria cultura</a>
                        <small class="block"><a href="#" class="">Descontos</a> <span class="label label-success">Ativa</span></small>
                        <small class="block">Promoções exclusivas para o Incentiv, a partir de 50 incentivs com descontos de 10% na compra de livros.</small>
                    </div>
                </article>
                <div class="line pull-in"></div>
                <article class="media">
                    <span class="pull-left thumb-small"><i class="fa fa-user fa fa-2x text-muted"></i></span>                
                    <div class="media-body">
                        <div class="pull-right media-mini text-center text-muted">
                            <strong class="h4">17</strong><br>
                            <small class="label bg-light">feb</small>
                        </div>
                        <a href="#" class="h4">Saraiva</a>
                        <small class="block"><a href="#" class="">Descontos</a> <span class="label label-success">Ativa</span></small>
                        <small class="block">A Saraiva em parceria com Incentiv está com descontos de até 50%, a partir de 80 incentivs</small>
                    </div>
                </article>
                <div class="line pull-in"></div>
                <article class="media">
                    <div class="media-body">
                        <div class="pull-right media-mini text-center text-muted">
                            <strong class="h4">09</strong><br>
                            <small class="label bg-light">jan</small>
                        </div>
                        <a href="#" class="h4 text-success">Curso de Inglês Wizard‎</a>
                        <small class="block">Obtenha 30% de desconto na matrícula, com apenas 50 incentivs</small>
                    </div>
                </article>
            </section>
        </section>
        <!-- / scrollable inbox widget-->
    </div>
</div>