<table class="table table-striped b-t text-small">
    <tbody>
        {% for campaign in page.items %}
        <tr>
            <td>{{ campaign.nome|e}}</td>
            <td>{{ campaign.matricula}}</td>
            <td>{{ campaign.email}}</td>
            <td>{{ campaign.status == 'S' ? 'Sim' : 'Não'}}</td>
            <td class="text-right">
                <div class="btn-group">
                    <button class="dropdown-toggle" role="button" data-toggle="dropdown"><i class="fa fa-gear"></i></button>
                    <ul class="dropdown-menu pull-right">
                        {% if(campaign.status == 'N') %}
                        <li class="text-left"><a href="#"><i class="icon-plus-sign"></i> Ativar</a>
                            {% else %}
                        <li class="text-left"><a href="#"><i class="fa fa-minus-square-o"></i> Inativar</a>
                            {% endif %}
                        <li class="text-left"><a href="#"><i class="icon-pencil"></i> Alterar</a> 
                        <li class="divider"></li>
                        <li class="text-left"><a href="#"><i class="icon-remove"></i> Deletar</a> </li>
                    </ul>
                </div>
            </td>
        </tr>
        {% elsefor %}
        <tr><td colspan="5" class="text-center text-info">Nenhum colaborador encontrado.</td></tr>
        {% endfor %}
    </tbody>
</table>
<footer class="panel-footer">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-3 text-center">
                <small class="text-muted inline m-t-small m-b-small">Mostrando {{ page.current }} de {{ page.total_pages }}</small>
            </div>
            <div class="col-sm-5 text-right text-center-sm">                
                <ul class="pagination pagination-small m-t-none m-b-none">
                    <li><a href="#" class="fa btnPaginacao" id="1"><i class="icons icon-fast-backward"></i> Primeiro</a></li>
                    <li><a href="#" class="fa btnPaginacao" id="{{page.before}}"><i class="icons icon-step-backward"></i> Anterior</a></li>
                    <li><a href="#" class="fa btnPaginacao" id="{{page.next}}"><i class="icons icon-step-forward"></i> Próximo</a></li>
                    <li><a href="#" class="fa btnPaginacao" id="{{page.last}}">Último <i class="icons icon-fast-forward"></i> </a></li>
                </ul>
            </div>
        </div>
</footer>
{{ javascript_include('js/empresa/colaboradores/pesquisar-colaboradores.js') }}
<script type="text/javascript">  
    $(document).ready(function(){
        pesquisarColaboradores.init();
    });       
</script>