<table class="table table-striped m-b-none text-small">
    <thead>
        <tr>
            <th class="col-lg-3">Progresso da Campanha</th>
            <th>Nome da Campanha</th>                    
            <th>Data de Início</th>                    
            <th>Data de fim</th>                    
            <th width="50"></th>
        </tr>
    </thead>
    <tbody>
        {% for campanha in campanhas %}
        <tr>
            <td>
                <div class="progress progress-small progress-striped active m-t-mini m-b-none">
                    <div class="progress-bar progress-bar-success" data-toggle="tooltip" data-original-title="80%" style="width: 80%"></div>
                </div>
            </td>
            <td>{{ campanha.regra}}</td>
            <td>{{ campanha.inicioDt}}</td>
            <td>{{ campanha.fimDt }}</td>
            <td class="text-right">
                <div class="btn-group">
                    <button class="dropdown-toggle" role="button" data-toggle="dropdown"><i class="fa fa-gear"></i></button>
                    <ul class="dropdown-menu pull-right">
                        {% if(campanha.ativo == 'N') %}
                        <li class="text-left"><a href="#"><i class="icon-plus-sign"></i> Ativar</a>
                            {% else %}
                        <li class="text-left"><a href="#"><i class="fa fa-minus-square-o"></i> Inativar</a>
                            {% endif %}
                        <li class="text-left"><a href="#"><i class="icon-pencil"></i> Alterar</a> 
                        <li class="divider"></li>
                        <li class="text-left"><a href="#"><i class="icon-remove"></i> Deletar</a> </li>
                    </ul>
                </div>
            </td>
        </tr>
        {% elsefor %}
        <tr><td colspan="5" class="text-center">Nenhuma campanha encontrada.</td></tr>
        {% endfor %}
    </tbody>
</table>