<div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Incentiv Admin</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                    {%- set menus = [
                    'Home': null,
                    'Usuários': 'users',
                    'Perfis': 'profiles',
                    'Permissões': 'permissions'
                    ] -%}
                    {%- for key, value in menus %}
                    {% if value == dispatcher.getControllerName() %}
                    <li class="active">{{ link_to(value, key) }}</li>
                    {% else %}
                    <li>{{ link_to(value, key) }}</li>
                    {% endif %}
                    {%- endfor -%}
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ auth.getName() }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>{{ link_to('users/changePassword', 'Change Password') }}</li>
                    </ul>
                </li>
                <li>{{ link_to('session/logout', 'Logout') }}</li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
          </div> <!-- /container -->
      <div class="container">
      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
            {{ content() }}
      </div>
      </div>

