<!--start navigation-->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container" data-start="padding: 15px 0px;" data-200="padding: 0px 0px;">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-responsive-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/incentiv" class="navbar-brand margin"><span class="incentiv">Incentiv </span><span class="go">Go</span> beta</a>
            <div class="collapse navbar-collapse" id="navbar-responsive-collapse">
                <div class="navbar-right">
                    <div class="navbar-btn">
                        {{ link_to("", 'class':'btn btn-link squared', "Voltar") }}
                    </div>
                </div>
            </div>
        </div>
    </nav>
<!--end navigation-->
{{ content() }}