<!--main content start-->
<div class="col-lg-9">
    <div class="row ">
          <div class="col-md-12">
            <!-- PONTUAÇÃO -->
            <div class="white-panel pn white-panel-ideia">
                <div class="white-header">
                    <h5>{{lang['ideias']}}</h5>
                </div>
                <div class="row pager">
                    <div class="col-md-6">
                        <p class="mt">{{lang['msg_ideia_enviadas']}}</p>
                        <span class="badge bg-primary">+ {{pontuacaoIdeiaEnviada}}</span> incentivs 
                    </div>
                    <div class="col-md-6">
                        <p class="mt">{{lang['msg_ideia_aprovadas']}}</p>
                        <span class="badge bg-primary">+ {{pontuacaoIdeiaAprovada}}</span> incentivs 
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <button class="btn btn-theme04 btn-facebook btn-sm" id="btnIdeias" type="button">{{lang['banco_de_ideias']}}</button>
                    </div>
                </div>
            </div>
        </div><!-- /col-md-4 -->
    </div><!-- /row -->
</div><!-- /col-lg-9 END SECTION MIDDLE -->
<!-- Início Modal Ideias -->
<div class="modal fade" id="modalIdeias" tabindex="-5" role="dialog" aria-labelledby="modalIdeias" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header modal-header-ideia">
                <div class="pull-right">
                    <button type="button" class="btn btn-default btn-modal-title" id="btnEnviarIdeia">{{lang['enviar_ideia']}}</button>
                    <button type="button" class="close close-title-btn"  data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">{{lang['fechar']}}</span></button>
                </div>
                <h4 class="modal-title" id="myModalLabelIdeias"></h4>
            </div>
            <div id="modal-body-ideias" class="modal-body"></div>
            <div class="modal-footer ">
            </div>
        </div>
    </div>
</div>
{{hidden_field("lang",'value':lang['lang'])}}
<!-- Fim Modal Ideias -->

{{ javascript_include('js/colaborador/ideia/ideia.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        Ideia.init($("#lang").val());
    });
</script>