<section class=" tasks-widget">
        <div class="task-content">
            <div id="mensagem-modal-resposta-ideias"><?php echo $this->flashSession->output(); ?></div>
            <ul class="task-list ui-sortable-modal ul-ideias" id="sortable" >
                {% for ideia in ideias %}
                <li class="list-primary" id="li_ideia_{{ideia.id}}">
                    <div class="task-title">
                        <span class="task-title-sp">{{ideia.descricao}}</span>
                    </div><br/>
                    <div class="task-title pull-left">
                        <span class="sp-title">Enviada em: {{ date('d/m/Y', ideia.criacaoDt) }}</span>
                    </div>
                    <div id={{ideia.id}} class="task-title pull-right">
                        {%if(ideia.criacaoDt != '' AND ideia.resposta == '' )%}
                            <span class="badge bg-important">Aguardando Aprovação</span>
                        {%elseif(ideia.resposta == "Y")%}
                            <span class="badge bg-info">Parabéns!!! Ideia aprovada</span>
                        {%endif%}
                    </div>
                </li>
                {% elsefor %}
                <li class="list-primary text-center">
                    <div class="task-title">
                        <span class="task-title-sp">Nenhuma ideia enviada até o momento!!!</span>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <div id="ul_ideia" class="container-fluid box1" style="display: none">
                    <form role="form" class="form-ideia" id="form-ideia">
                        <div class="form-group col-lg-12"> 
                            <input type="text" id="txt_titulo" name="txt_titulo" placeholder="Informe um título para a ideia!!!" class="form-control"></textarea>
                            <label id="txt_tituloId-error" class="error pull-left display-none"  for="txt_titulo">Campo obrigatório</label>
                        </div><br/>
                        <div class="form-group col-lg-12"> 
                            <textarea id="txt_ideia" name="txt_ideia" placeholder="Descreva sua ideia, envie e seja reconhecido pela empresa!!!" class="form-control"></textarea>
                            <label id="txt_ideiaId-error" class="error pull-left display-none"  for="txt_ideia">Campo obrigatório</label>
                        </div><br/>
                    </form>
                    <div class="form-group pull-right">
                        <button type="button" id="btnSalvarIdeia" class="btn btn-xs btn-facebook">Enviar</button>
                        <button type="button" id="btnCancelarIdeia" class="btn btn-xs btn-default">Cancelar</button>
                    </div>
            </div>
    </div>
</section>
{{ javascript_include('js/colaborador/ideia/modal-ideias.js') }}
<script type="text/javascript">  
    $(document).ready(function(){
        ModalIdeias.init();
    });   
</script>