<!--start navigation-->
    <div class="navbar navbar-fixed-top" role="navigation">
        <div class="container" data-start="padding: 15px 0px;" data-200="padding: 0px 0px;">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/incentiv" class="navbar-brand margin">Incentiv beta</a>
            <div class="nav-collapse collapse navbar-responsive-collapse pull-right">
                <div class="navbar-btn">
                    {{ link_to("session/logout", 'class':'btn btn-link squared', "Sair") }}
                </div>
            </div>
        </div>
    </div>
<!--end navigation-->
{{ content() }}