<!--main content start-->
<div class="col-lg-9">
    <div class="row">
        <div class="col-lg-4 mb">
            <!-- PONTUAÇÃO -->
            <div class="white-panel pn">
                <div class="white-header">
                    <h5>Pontuação</h5>
                </div>
                <div class="badge badge-popular"><h2>{{count_pontuacao}}</h2></div>
                <p><b>pontos</b></p>
                <div class="col-lg-12">
                    <div class="col-lg-6 small">
                        <p class="mt"><h6>Pontos ganhos</h6></p>
                    <p><h6>{{count_pontuacao_ganha}} pontos</h6></p>
                    </div>
                    <div class="col-lg-6 small">
                        <p class="mt"><h6>Pontos usados</h6></p>
                    <p><h6>{{count_pontuacao_usada}} pontos</h6></p>
                    </div>
                </div>
            </div>
        </div><!-- /col-md-4 -->

        <!-- DESAFIOS -->
        <div class="col-md-4 col-sm-4 mb">
            <div class="white-panel pn">
                <div class="white-header">
                    <h5>Desafios <span class="badge bg-theme">{{count_desafios}}</span></h5>
                </div>
                <div class="row">
                    <div class="col-sm-4 col-xs-4"></div>
                </div>
                <div class="centered">
                    <!--<h1> <span class="fa fa-clock-o fa-2x"></span></h1>-->
                    <h1> <span class="fa fa-th-large fa-2x"></span></h1>
                </div>
                <button class="btn btn-link" id="btnEncarar">Encarar</button>
            </div>
        </div><!-- /col-md-4 -->

        <!-- NOTÍCIAS -->
        <div class="col-md-4 col-sm-4 mb">
            <div class="white-panel pn">
                <div class="white-header">
                    <h5>Ajudas <span class="badge bg-theme04">{{count_ajudas}}</span></h5>
                </div>
                <div class="row">
                    <div class="col-sm-4 col-xs-4"></div>
                </div>
                <div class="centered">
                    <h1> <span class=" li_fire fa-2x"></span></h1>
                </div>
                <button class="btn btn-link" id="btnAjuda">Pedir ajuda</button>
            </div>
        </div><!-- /col-md-4 -->
        <div class="col-md-2 col-sm-2 col-lg-offset-8 mb">
            <div class="white-panel pn">
                <div class="white-header">
                    <h5>Notícias <span class="badge bg-theme03">{{count_noticias}}</span></h5>
                </div>
                <div class="row">
                    <div class="col-sm-4 col-xs-4"></div>
                </div>
                <div class="centered">
                    <h1> <span class=" li_news"></span></h1>
                </div>
                <button class="btn btn-theme03" id="btnVerNoticias">Ver</button>
            </div>
        </div><!-- /col-md-4 -->
        <div class="col-md-2 col-sm-2 mb">
            <div class="white-panel pn">
                <div class="white-header">
                    <h5>Anotações <span class="badge bg-theme02">{{count_anotacoes}}</span></h5>
                </div>
                <div class="row">
                    <div class="col-sm-6 col-xs-6"></div>
                </div>
                <div class="centered">
                    <h1> <span class=" li_pen"></span></h1>
                </div>
                <button class="btn btn-theme02" id="btnInserirAnotacoes">Inserir</button>
            </div>
        </div><!-- /col-md-4 -->
<!--                        <div class="col-md-8 col-sm-8 mb">
            <div class="white-panel panel panel-body">
                <div class="col-md-4 col-sm-4">

                        <h5 class="">Ajudas <span class="badge bg-theme02">4</span></h5>

                    <div class="row">
                        <div class="col-sm-4 col-xs-4"></div>
                    </div>
                    <div class="centered">
                        <h1> <span class=" li_pen"></span></h1>
                    </div>
                    <button class="btn-link">Pedir Ajuda</button>
                </div>

                <div class="col-md-4 col-sm-4">
                    <div class="white-panel">
                        <h5>Conhecimentos <span class="badge bg-important">4</span></h5>
                    </div>
                    <div class="row">
                        <div class="col-sm-4 col-xs-4"></div>
                    </div>
                    <div class="centered">
                        <h1> <span class=" li_pen"></span></h1>
                    </div>
                    <button class="btn-link btn-gplus">Gerar Conhecimento</button>
                </div>
            </div>
        </div> /col-md-4   -->
    </div><!-- /row -->
</div><!-- /col-lg-9 END SECTION MIDDLE -->

<!-- Início Modal Desafios -->
<div class="modal fade" id="modalDesafios" tabindex="-5" role="dialog" aria-labelledby="modalDesafios" aria-hidden="true">
    {{ form('empresa/colaborador/salvar-desafio', 'class':'form-horizontal', 'id':'form-colaborador', 'method': 'post') }}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header modal-header-desafio">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title" id="myModalLabelDesafios"></h4>
            </div>
            <div id="modal-body-desafios" class="modal-body"></div>
            <div class="modal-footer"> </div>
        </div>
    </div>
    {{endForm()}}
</div>
<!-- Fim Modal Desafios -->
<!-- Início Modal Ajudas -->
<div class="modal fade" id="modalAjudas" tabindex="-5" role="dialog" aria-labelledby="modalAjudas" aria-hidden="true">

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header modal-header-ajuda">
                <div class="pull-right">
                    <button type="button" class="btn btn-default btn-modal-title" id="btnPedirAjuda">Pedir ajuda</button>
                    <button type="button" class="close close-title-btn"  data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                </div>
                <h4 class="modal-title" id="myModalLabelAjudas"></h4>
            </div>
            {{ form('empresa/colaborador/salvar-desafio', 'class':'form-horizontal', 'id':'form-ajudas', 'method': 'post') }}
            <div id="modal-body-ajudas" class="modal-body"></div>
            {{endForm()}}
            <div class="modal-footer ">
                <div id="modal-footer-ajuda" style="display: none;">
                    <div class="task-title inline"> 
                        <form role="form" class="form-ajudar" id="form_ajudar">
                            <div>
                                <textarea id="txt_mensagem_ajudar" name="txt_mensagem_ajudar" placeholder="Ajudar" class="form-control"></textarea>
                            </div>
                        </form>
                    </div><br/>
                    <div class="task-title pull-right">
                        <button type="button" id="btnAjudaEnvio" class="btn btn-xs btn-theme03">Enviar</button>
                        <button type="button" id="btnCancelarAjuda" class="btn btn-xs btn-theme04">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fim Modal Ajudas -->
<!-- Início Modal Notícias -->
<div class="modal fade" id="modalNoticias" tabindex="-5" role="dialog" aria-labelledby="modalNoticias" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header modal-header-noticia">
                <div class="pull-right">
                    <button type="button" class="close close-title-btn"  data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                </div>
                <h4 class="modal-title" id="myModalLabelNoticias"></h4>
            </div>
            <div id="modal-body-noticias" class="modal-body"></div>
            <div class="modal-footer "></div>
        </div>
    </div>
</div>
<!-- Fim Modal Notícias -->
<!-- Início Modal Anotacões -->
<div class="modal fade" id="modalAnotacoes" tabindex="-5" role="dialog" aria-labelledby="modalAnotacoes" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header modal-header-anotacao">
                <div class="pull-right">
                    <button type="button" class="btn btn-default btn-modal-title" id="btnAnotar">Anotar</button>
                    <button type="button" class="close close-title-btn"  data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                </div>
                <h4 class="modal-title" id="myModalLabelAnotacoes"></h4>
            </div>
            <div id="modal-body-anotacoes" class="modal-body"></div>
            <div class="modal-footer ">
            </div>
        </div>
    </div>
</div>
<!-- Fim Modal Anotações -->
{{ javascript_include('js/colaborador/index/colaborador.js') }}
<script type="text/javascript">
    $(document).ready(function() {
        Colaborador.init();
    });
</script>