<section class=" tasks-widget">
        <div class="task-content">
            <ul class="task-list ui-sortable-modal ul-noticias" id="sortable" >
                {% for noticia in noticias %}
                <li class="list-primary" id="li_noticia_{{noticia.id}}">
                    <div class="task-title">
                        <span class="task-title-sp">{{noticia.mensagem}}</span>
                    </div><br/>
                    <div class="task-title pull-left">
                        <span class="sp-title moment">{{date(noticia.envioDt)}}</span>
                    </div>
                </li>
                {% elsefor %}
                <li class="list-primary text-center">
                    <div class="task-title">
                        <span class="task-title-sp">Nenhuma notícia no momento!!!</span>
                    </div>
                </li>
                {% endfor %}
            </ul>
    </div>
</section>
<!-- Fim Modal Cadastro colaborador -->
{{ javascript_include('js/colaborador/index/modal-noticias.js') }}
<script type="text/javascript">  
    $(document).ready(function(){
        ModalNoticias.init();
    });   
</script>